#!/usr/bin/perl
use strict;
use Test::More;

use Crypt::Mcrypt;

my @data = <DATA>;
plan tests => scalar(@data);

#
# Compare our output with the test output generated by
# "known/generate_testcases.c" (included as the DATA section in this
# program)
#

$. = 1; # hack since moving from while (<DATA>)
foreach (@data) {
    chomp;
    my %testcase = map { split('=',$_,2) } split(/,/,$_);
    foreach (qw(key iv pt ct)) {
        $testcase{$_} = decode_bin($testcase{$_});
    }
    run_testcase(%testcase);
}
continue {
    $.++;
}

sub run_testcase {
    my %tc = @_;

    my ($algo,$mode,$key,$iv,$pt,$ct) = @tc{qw(algo mode key iv pt ct)};

    my $mc = Crypt::Mcrypt->new(algo => $algo, mode => $mode);
    $mc->key($key) if defined $key;
    $mc->iv($iv) if defined $iv;

    my $tc_ciphertext = $mc->encrypt($pt);
    if (!defined $tc_ciphertext) {
        return nope("encrypt - undefined");
    }
    if ($tc_ciphertext ne $ct) {
        printf STDERR "expected %s\n", encode_bin($ct);
        printf STDERR "     got %s\n", encode_bin($tc_ciphertext);
        return nope("encrypt output match");
    }

    my $tc_plaintext = $mc->decrypt($ct);
    if (!defined $tc_plaintext) {
        return nope("decrypt - undefined");
    }
    if ($tc_plaintext ne $pt) {
        printf STDERR "expected %s\n", encode_bin($pt);
        printf STDERR "     got %s\n", encode_bin($tc_plaintext);
        return nope("decrypt output match");
    }

    return yep();
}

sub yep  { ok(1, "testcase $.") }
sub nope { my $place = shift; ok(0, "testcase $. - $place") }

sub decode_bin {
    my $binstr = shift;
    if (!length($binstr)) {
        return undef;
    }
    return pack('C*', map { hex($_) } split(' ',$binstr));
}

sub encode_bin {
    my $bin = shift;
    if (!length($bin)) {
        return undef;
    }
    return join(' ', map { sprintf("%02x",$_) } unpack('C*', $bin));
}

__DATA__
algo=cast-128,mode=cbc,key=d5 b5 c1 f3 1a 41 a1 e2 b3 1e ca 17 4c 66 21 26,iv=f6 bc 88 6b 61 b7 5f ef,pt=6d 31 81 13 48 9f d6 d2,ct=06 1b ce bf e5 38 24 b2
algo=cast-128,mode=cfb,key=e8 4e e6 d6 9d b9 74 67 c1 ae d3 ee c5 d2 58 e2,iv=a6 0b 46 09 f8 91 47 94,pt=b5 ea e7 15 c0,ct=b3 9a 84 74 fb
algo=cast-128,mode=cfb,key=e8 4e e6 d6 9d b9 74 67 c1 ae d3 ee c5 d2 58 e2,iv=a6 0b 46 09 f8 91 47 94,pt=90 d5 7e 6a 97 23 b3 bc,ct=96 c1 6e dd 37 e7 81 ff
algo=cast-128,mode=ctr,key=35 93 db 04 4e af cd f8 d9 86 fa 55 25 3d fd 50,iv=b8 f7 78 56 7e f6 06 65,pt=1f 69 a1 58 5b,ct=eb f1 0f 5d 90
algo=cast-128,mode=ctr,key=35 93 db 04 4e af cd f8 d9 86 fa 55 25 3d fd 50,iv=b8 f7 78 56 7e f6 06 65,pt=6e 9c c4 7c d7 65 be 71,ct=9a 04 6a 79 1c ad 7d 51
algo=cast-128,mode=ecb,key=91 5a 34 71 67 dc 39 d4 62 63 e5 3b fe b3 08 cf,iv=1b af 50 c6 3f 43 78 cf,pt=60 fb 54 7f 05 00 3a 81,ct=3e a4 ac 9d 7a 4d c1 ee
algo=cast-128,mode=ncfb,key=f3 4a 74 a4 20 1e 47 13 b2 ec 03 ce 6c 8d 8d 3a,iv=0d 16 0c 9f bc c6 ef 34,pt=85 20 69 1e 62,ct=40 57 4b 8c c1
algo=cast-128,mode=ncfb,key=f3 4a 74 a4 20 1e 47 13 b2 ec 03 ce 6c 8d 8d 3a,iv=0d 16 0c 9f bc c6 ef 34,pt=1d 4e 08 36 43 18 78 0a,ct=d8 39 2a a4 e0 83 b5 b1
algo=cast-128,mode=nofb,key=90 ce 02 21 f4 40 77 d6 26 63 c3 75 42 30 7a 68,iv=fa 6e f9 6c de 18 19 b6,pt=25 f2 fc d4 0c,ct=8e fd 70 4d 15
algo=cast-128,mode=nofb,key=90 ce 02 21 f4 40 77 d6 26 63 c3 75 42 30 7a 68,iv=fa 6e f9 6c de 18 19 b6,pt=f5 12 72 71 e3 83 b0 88,ct=5e 1d fe e8 fa 7c b1 4c
algo=cast-128,mode=ofb,key=f9 7f c3 84 ce df 8b 91 aa e4 c2 71 b7 0f 34 bf,iv=22 09 fe d4 e5 5b b8 d7,pt=23 3b d5 b0 49,ct=03 40 44 f1 35
algo=cast-128,mode=ofb,key=f9 7f c3 84 ce df 8b 91 aa e4 c2 71 b7 0f 34 bf,iv=22 09 fe d4 e5 5b b8 d7,pt=3d 51 01 28 21 01 c1 6a,ct=1d 2a 90 69 5d 2e e7 5a
algo=gost,mode=cbc,key=8c d0 b7 1b c6 10 cf f5 2d ec b3 57 4b 00 77 a5 cc 5c 73 3d 41 31 62 a5 6a 5d 7f 01 71 56 4d a9,iv=ea a6 a6 4f 72 c8 52 7f,pt=da f1 57 64 71 44 5f 7d,ct=df 2a af 73 4e 5b a4 bf
algo=gost,mode=cfb,key=7a e6 ee b0 42 87 b6 1f 4d 76 71 af d6 94 dd a9 11 02 40 6e 62 b1 74 15 aa e7 ad e5 e5 7a 00 ef,iv=c2 4e 76 9a 15 f1 ab 6f,pt=3d 5a f8 5e ac,ct=a1 50 05 44 2d
algo=gost,mode=cfb,key=7a e6 ee b0 42 87 b6 1f 4d 76 71 af d6 94 dd a9 11 02 40 6e 62 b1 74 15 aa e7 ad e5 e5 7a 00 ef,iv=c2 4e 76 9a 15 f1 ab 6f,pt=70 e0 fa 1c 71 19 ae 56,ct=ec 1d 14 db 15 d5 51 24
algo=gost,mode=ctr,key=e9 a0 90 9f 91 64 12 b3 f0 2a 7e 78 86 30 40 a4 ab a0 ee 1e b1 75 cb 22 53 4d f4 f5 6f 9f 9e 61,iv=37 85 cc 23 a0 c2 81 0d,pt=42 8c 42 52 be,ct=c0 f7 89 24 51
algo=gost,mode=ctr,key=e9 a0 90 9f 91 64 12 b3 f0 2a 7e 78 86 30 40 a4 ab a0 ee 1e b1 75 cb 22 53 4d f4 f5 6f 9f 9e 61,iv=37 85 cc 23 a0 c2 81 0d,pt=98 8d 79 ce 68 5d 9d fa,ct=1a f6 b2 b8 87 b1 61 17
algo=gost,mode=ecb,key=1c 68 a6 56 5f b5 27 46 d5 dd dd c2 a5 f1 85 d2 b1 84 59 86 ec 74 5b 97 d3 c3 4b 7f 94 56 fa 8e,iv=e6 db f6 61 b0 50 cf f5,pt=81 a3 a3 d7 8a 8c 51 79,ct=b4 18 e4 d3 78 3d ee 45
algo=gost,mode=ncfb,key=74 a6 8d 71 90 75 25 9a 2c 29 0a ab 5a 8b 65 62 91 95 ee 1b a0 93 e9 82 02 22 96 49 98 4a 4d 6e,iv=5d 2a 22 61 5a d0 6e 00,pt=7d b1 a3 00 53,ct=53 22 e7 46 87
algo=gost,mode=ncfb,key=74 a6 8d 71 90 75 25 9a 2c 29 0a ab 5a 8b 65 62 91 95 ee 1b a0 93 e9 82 02 22 96 49 98 4a 4d 6e,iv=5d 2a 22 61 5a d0 6e 00,pt=19 8d e5 93 00 ce 89 0d,ct=37 1e a1 d5 d4 cf 50 b2
algo=gost,mode=nofb,key=3d c7 65 9f a1 ad 3d 40 67 1b a2 c5 38 4d 93 33 8f a7 f7 0c de da 66 de af dc e5 b5 bc a1 43 9e,iv=85 33 b8 4c 7b 7a 5b ab,pt=3b d0 69 06 24,ct=58 fa b4 92 c5
algo=gost,mode=nofb,key=3d c7 65 9f a1 ad 3d 40 67 1b a2 c5 38 4d 93 33 8f a7 f7 0c de da 66 de af dc e5 b5 bc a1 43 9e,iv=85 33 b8 4c 7b 7a 5b ab,pt=ac c7 f3 86 e5 08 3d af,ct=cf ed 2e 12 04 51 1a a0
algo=gost,mode=ofb,key=0d 51 76 de bd c5 65 3c 1f 4a aa 6a ad d3 d4 83 51 05 23 47 bb 58 a4 88 f0 06 fc 70 7c 25 e2 07,iv=68 65 76 7d 04 49 40 44,pt=6a ae 79 d5 fc,ct=db 19 63 f2 3c
algo=gost,mode=ofb,key=0d 51 76 de bd c5 65 3c 1f 4a aa 6a ad d3 d4 83 51 05 23 47 bb 58 a4 88 f0 06 fc 70 7c 25 e2 07,iv=68 65 76 7d 04 49 40 44,pt=43 6c 51 1c 3f aa b3 c2,ct=f2 db 4b 3b ff 6c 5c 01
algo=rijndael-128,mode=cbc,key=62 56 b4 0d 49 28 a0 45 ca b4 a7 c0 96 ed 80 de,iv=c9 17 d6 d3 bf 76 77 88 50 36 88 53 9d 1b 22 02,pt=59 af 41 94 01 73 c4 8a 2c 65 3b 98 3d 0c 1b 23,ct=62 e1 ee a5 9b ad 6b 94 e9 66 01 11 47 8a 8b cf
algo=rijndael-128,mode=cbc,key=4e df 51 46 49 af 91 b7 51 51 1a bb e4 a9 63 a2 42 9d 01 d5 20 6d 18 c6,iv=a4 b3 18 f0 be 46 b3 64 6f 45 f1 f4 a3 fd 4d b8,pt=68 23 bf c7 df 5e a4 14 02 c5 34 8f 12 4c 10 e4,ct=0c 0a 02 f4 94 01 9f 06 7d 08 51 14 08 7d a7 b9
algo=rijndael-128,mode=cbc,key=54 86 62 78 88 38 f4 a1 be 2e 6e bc 4b 79 0b b7 b0 6a 77 94 f3 10 eb ea 15 a0 65 dc 74 3d e4 97,iv=ed b7 37 0a e7 c9 1e 69 aa 88 6b 9b b2 e0 40 3d,pt=86 f6 59 55 f3 2f e9 d9 01 e0 19 23 ef 03 8a e3,ct=f7 9b 5c 4d 7b 5f 3d 6c 47 03 64 1e ea b6 2d 5c
algo=rijndael-128,mode=cfb,key=59 c6 cd d1 79 b8 29 33 cf b1 5b 07 f6 f6 06 fd,iv=99 fa 05 52 28 12 87 21 7f 60 99 22 9f 2e 4a e4,pt=f2 36 2b 80 1e,ct=11 80 12 ed fe
algo=rijndael-128,mode=cfb,key=59 c6 cd d1 79 b8 29 33 cf b1 5b 07 f6 f6 06 fd,iv=99 fa 05 52 28 12 87 21 7f 60 99 22 9f 2e 4a e4,pt=8d e4 0d 10 dc 55 c4 7c aa 2e 3c 8a 17 16 da b7,ct=6e 21 d6 f9 80 3b 6f 94 8c 44 48 b9 13 4e 1e 13
algo=rijndael-128,mode=cfb,key=e5 bd 74 f0 38 21 ec c9 8b 96 07 d0 de bf b2 74 9a 03 f9 39 ab 29 73 bf,iv=c7 e3 23 d7 5d 74 1b 0e 5c e1 c7 62 d4 58 70 cb,pt=f4 2e aa 4a c6,ct=16 50 ec 71 14
algo=rijndael-128,mode=cfb,key=e5 bd 74 f0 38 21 ec c9 8b 96 07 d0 de bf b2 74 9a 03 f9 39 ab 29 73 bf,iv=c7 e3 23 d7 5d 74 1b 0e 5c e1 c7 62 d4 58 70 cb,pt=fd 88 54 5d d0 b2 d1 57 6e 12 90 bf c4 54 5c 4f,ct=1f 37 cd 84 70 d2 e2 a4 56 12 4a 09 5f 82 95 39
algo=rijndael-128,mode=cfb,key=49 07 c7 cf 74 ed 96 82 a5 7d a6 ca a9 2b 4b bd 4e 38 13 04 29 34 22 ab d3 81 65 32 f2 46 48 57,iv=2e 81 ce d4 45 be ea 4b 21 2a 4d e3 43 51 e3 c1,pt=d6 16 3d 5d 69,ct=bb ce c3 9c 76
algo=rijndael-128,mode=cfb,key=49 07 c7 cf 74 ed 96 82 a5 7d a6 ca a9 2b 4b bd 4e 38 13 04 29 34 22 ab d3 81 65 32 f2 46 48 57,iv=2e 81 ce d4 45 be ea 4b 21 2a 4d e3 43 51 e3 c1,pt=68 3c 24 b1 85 cd 7d cb 08 5f c8 a1 d2 da 28 61,ct=05 92 ad a0 2d 84 af c5 60 7f fb e6 a7 a7 98 9d
algo=rijndael-128,mode=ctr,key=d8 9f f1 eb 1b 6f 6f 8c 02 62 2b b3 0f fb 54 78,iv=9b ab 6a 36 f1 b7 87 bc 6c 14 d0 27 d6 d3 5c 48,pt=72 17 8f 52 28,ct=8b 54 31 bc 86
algo=rijndael-128,mode=ctr,key=d8 9f f1 eb 1b 6f 6f 8c 02 62 2b b3 0f fb 54 78,iv=9b ab 6a 36 f1 b7 87 bc 6c 14 d0 27 d6 d3 5c 48,pt=43 38 8d 8f 84 11 2a 34 94 79 51 4e 62 a7 ac 6f,ct=ba 7b 33 61 2a 73 96 f9 f3 5f e2 05 3d 97 3a 17
algo=rijndael-128,mode=ctr,key=e7 28 c3 35 eb eb ad 7d 91 db f1 c1 82 44 53 f0 da e3 c6 56 34 66 55 ca,iv=88 1c 94 d2 4a 40 5c 76 3b cc 21 ab b8 56 a6 08,pt=80 b5 11 7a 87,ct=a7 e5 3d 23 77
algo=rijndael-128,mode=ctr,key=e7 28 c3 35 eb eb ad 7d 91 db f1 c1 82 44 53 f0 da e3 c6 56 34 66 55 ca,iv=88 1c 94 d2 4a 40 5c 76 3b cc 21 ab b8 56 a6 08,pt=91 f9 d0 6c 8f a5 f8 59 61 cc 55 dd 67 aa 48 13,ct=b6 a9 fc 35 7f d3 e1 f3 38 eb f0 a7 52 35 46 c8
algo=rijndael-128,mode=ctr,key=62 7f e0 25 bf a3 35 21 f9 56 8d a4 b8 2a e1 4b c6 12 b6 25 66 da e4 3c 8f c4 36 fe 1b ea 67 a9,iv=f7 d3 a8 ef a1 29 55 f6 55 e1 42 7f 59 ed f0 79,pt=0e b4 64 fc 9e,ct=bb e4 51 e3 57
algo=rijndael-128,mode=ctr,key=62 7f e0 25 bf a3 35 21 f9 56 8d a4 b8 2a e1 4b c6 12 b6 25 66 da e4 3c 8f c4 36 fe 1b ea 67 a9,iv=f7 d3 a8 ef a1 29 55 f6 55 e1 42 7f 59 ed f0 79,pt=1a 7a f4 34 21 41 c3 44 45 a1 e0 6f 45 48 41 8e,ct=af 2a c1 2b e8 63 a7 8f 97 c4 b0 95 ac 25 be b3
algo=rijndael-128,mode=ecb,key=c7 aa e8 e8 8e 0a 56 e3 5c 15 b3 99 30 94 04 63,iv=c8 78 71 59 09 e3 14 87 02 1a cf e6 32 40 58 6d,pt=c8 57 82 32 fe f6 6d c5 7f b9 2e 0d 13 89 27 70,ct=be f3 ee 2f 8a f6 d4 70 91 1c 60 9f 83 29 b4 af
algo=rijndael-128,mode=ecb,key=46 b4 7b fe ed 5d 32 c4 43 96 f0 25 8d 44 85 48 fe 20 86 1f 0a 70 3c c3,iv=4c dc 0b ce 45 a0 f1 1c f8 a8 88 fc 5a 7e 3d e8,pt=b4 00 17 20 2e 85 47 b4 46 ef 75 e3 47 4f 18 d0,ct=9b b3 50 d9 98 2c 3d 30 24 3d 6c af f2 92 05 4a
algo=rijndael-128,mode=ecb,key=61 85 99 a5 c2 e1 71 2c a1 4e 59 bc 81 5f b9 74 d8 cd a8 3b 9e c1 88 b5 c7 48 6e a3 3d 30 68 80,iv=02 33 b6 41 c7 fc 64 10 d4 a0 49 1d bc 13 c6 fd,pt=5d 0d 1b 9e 11 ad 80 c8 d8 69 0c 9b 15 ec 47 c1,ct=0b 6a 14 eb 8e c2 87 5e e7 5d 7a 2f 42 ad 13 61
algo=rijndael-128,mode=ncfb,key=1e d7 2c 0d de 20 3b 08 b5 38 1e b3 8e 7e 50 c0,iv=dd a5 09 60 80 1a 05 8e 5c 8f 42 17 11 4c 79 e3,pt=76 31 9b 32 fc,ct=a3 70 04 75 1e
algo=rijndael-128,mode=ncfb,key=1e d7 2c 0d de 20 3b 08 b5 38 1e b3 8e 7e 50 c0,iv=dd a5 09 60 80 1a 05 8e 5c 8f 42 17 11 4c 79 e3,pt=d6 da fb 87 32 04 c8 96 56 e3 4f 7c 6b 86 1c 29,ct=03 9b 64 c0 d0 6b a8 39 a3 51 9e ee 06 4c 85 a4
algo=rijndael-128,mode=ncfb,key=d5 b9 ab 20 26 df 23 1f 56 a3 a2 44 38 30 48 e8 65 7f be bc fe 43 5d 3f,iv=f4 cd 37 bd 2f e2 55 0f ef 6d 0d 2d 3c 9b c3 41,pt=58 e3 57 83 12,ct=ec 92 34 61 d8
algo=rijndael-128,mode=ncfb,key=d5 b9 ab 20 26 df 23 1f 56 a3 a2 44 38 30 48 e8 65 7f be bc fe 43 5d 3f,iv=f4 cd 37 bd 2f e2 55 0f ef 6d 0d 2d 3c 9b c3 41,pt=19 59 9c d1 1a 47 3a ab ec 7c 3b 16 13 e5 df 2c,ct=ad 28 ff 33 d0 d7 d0 87 5e 2b 24 61 e4 f8 b5 88
algo=rijndael-128,mode=ncfb,key=2c ed 57 eb eb c9 ef 08 e9 eb c3 bd f7 16 b6 cd d0 87 10 4f 5a f1 f6 42 9a 1a 22 85 c7 21 8e 88,iv=40 87 11 9d 8e 01 e7 24 f2 aa 2f d9 13 1e 28 f4,pt=e6 d1 7d 02 28,ct=88 52 e2 f4 c1
algo=rijndael-128,mode=ncfb,key=2c ed 57 eb eb c9 ef 08 e9 eb c3 bd f7 16 b6 cd d0 87 10 4f 5a f1 f6 42 9a 1a 22 85 c7 21 8e 88,iv=40 87 11 9d 8e 01 e7 24 f2 aa 2f d9 13 1e 28 f4,pt=c6 97 39 f5 40 34 ce 96 72 62 18 f0 cb a4 e6 39,ct=a8 14 a6 03 a9 0d 75 05 2d 24 21 3f ea 04 ae ab
algo=rijndael-128,mode=nofb,key=b5 c1 41 42 6b 82 ad b2 68 4d ab 20 0d 8f cb c1,iv=0a a6 80 28 7c 9f 31 8e fb b8 f1 b6 31 54 c9 39,pt=2e 5c bb a1 c3,ct=b9 2c a1 44 c4
algo=rijndael-128,mode=nofb,key=b5 c1 41 42 6b 82 ad b2 68 4d ab 20 0d 8f cb c1,iv=0a a6 80 28 7c 9f 31 8e fb b8 f1 b6 31 54 c9 39,pt=24 1f fc db a4 ce 64 89 e3 c3 f9 8a 08 bc ca 31,ct=b3 6f e6 3e a3 ab 5c 37 64 3a 4e db 0e ee a5 79
algo=rijndael-128,mode=nofb,key=c1 48 ab 2d 48 46 82 a5 67 4f 8a 54 3c 9a b7 54 0c 35 23 9f af a8 0c eb,iv=6d b9 27 30 15 2f c7 29 e3 ef b1 d0 13 03 1e b5,pt=63 d2 03 93 f2,ct=d0 7d b0 c9 1b
algo=rijndael-128,mode=nofb,key=c1 48 ab 2d 48 46 82 a5 67 4f 8a 54 3c 9a b7 54 0c 35 23 9f af a8 0c eb,iv=6d b9 27 30 15 2f c7 29 e3 ef b1 d0 13 03 1e b5,pt=77 cb 3a b7 c2 47 12 72 a3 f6 b6 32 56 26 4f dc,ct=c4 64 89 ed 2b 5c 5e 12 b9 4e 27 bd df 7b 08 97
algo=rijndael-128,mode=nofb,key=be ab 01 f2 d9 c4 0a 16 bc a5 98 ed 19 db b7 e4 d2 4c 8f 4a 10 68 d9 fb 89 02 08 ec 58 13 37 21,iv=ae f5 e4 bb 68 42 a2 53 65 8e b7 c6 cc 2d 57 0d,pt=4a 7e 82 7a f7,ct=fe 99 e3 be 25
algo=rijndael-128,mode=nofb,key=be ab 01 f2 d9 c4 0a 16 bc a5 98 ed 19 db b7 e4 d2 4c 8f 4a 10 68 d9 fb 89 02 08 ec 58 13 37 21,iv=ae f5 e4 bb 68 42 a2 53 65 8e b7 c6 cc 2d 57 0d,pt=d6 a1 89 ce 4d fe fd 65 1b 87 72 80 d6 1a 1b 37,ct=62 46 e8 0a 9f d2 75 97 99 ab 3a 78 bb 72 fd c4
algo=rijndael-128,mode=ofb,key=6b 47 9d 45 cc 1f 5e c6 bf 2d 1f 41 ec 75 af 06,iv=a2 eb a4 64 d5 5c 49 f3 f8 c1 04 78 e1 de b2 e1,pt=4a 1c bc c7 89,ct=6a d0 d8 91 8f
algo=rijndael-128,mode=ofb,key=6b 47 9d 45 cc 1f 5e c6 bf 2d 1f 41 ec 75 af 06,iv=a2 eb a4 64 d5 5c 49 f3 f8 c1 04 78 e1 de b2 e1,pt=66 8a bb ce 05 9d 67 07 b8 e5 07 9f 8c df 8e e5,ct=46 46 df 98 03 98 c1 34 c3 bc e3 a5 e9 25 26 64
algo=rijndael-128,mode=ofb,key=cf 63 d4 97 9e a2 50 39 12 94 86 5e 38 52 84 e9 83 dc bd 29 9a 61 b3 71,iv=4c c7 93 5e 40 92 4d dd 77 a6 cd 51 a5 5e 8f ae,pt=39 6f 7a 92 7e,ct=f2 d1 4d bc 83
algo=rijndael-128,mode=ofb,key=cf 63 d4 97 9e a2 50 39 12 94 86 5e 38 52 84 e9 83 dc bd 29 9a 61 b3 71,iv=4c c7 93 5e 40 92 4d dd 77 a6 cd 51 a5 5e 8f ae,pt=15 1b 74 15 08 12 38 01 01 40 93 3a 88 16 b5 ec,ct=de a5 43 3b f5 e2 03 55 ee a9 9e 3a 8f 3a ac 6a
algo=rijndael-128,mode=ofb,key=2b c5 ca 0c 9c d0 61 80 65 12 54 4b b9 b9 f0 57 d7 53 80 94 f3 e8 70 0e b2 91 d2 fd fe ca 48 f3,iv=87 3b 5b 45 49 4d ec 95 7e 2f 07 d3 52 98 a0 cf,pt=d5 07 46 08 e2,ct=f1 bf 06 c7 4b
algo=rijndael-128,mode=ofb,key=2b c5 ca 0c 9c d0 61 80 65 12 54 4b b9 b9 f0 57 d7 53 80 94 f3 e8 70 0e b2 91 d2 fd fe ca 48 f3,iv=87 3b 5b 45 49 4d ec 95 7e 2f 07 d3 52 98 a0 cf,pt=67 9d 3e 14 c7 0a 7d 72 2f 98 38 df 0b 9d e6 d4,ct=43 25 7e db 6e bb c1 1d d9 d7 eb 2f 01 46 49 48
algo=twofish,mode=cbc,key=17 3c 5e bf 15 6c e4 27 1d a7 92 d6 57 fa 94 37,iv=90 9d 9c 60 38 ab 14 b3 78 1a 35 bc 33 1d 09 0a,pt=e4 57 51 a2 f1 49 98 a5 82 8d 56 7d fa 33 92 ef,ct=14 a4 53 35 fa 36 e1 23 70 be 19 2c fc d7 b6 be
algo=twofish,mode=cbc,key=26 2d e2 7c c7 be 77 e9 d1 07 3f 82 20 b9 ea 26 f4 e1 34 2b 1c d9 0a db,iv=3d 6d 28 7a ec 6f f7 9e ee f1 80 8c c8 e2 c8 ae,pt=51 24 03 9d 7d 15 ef 82 05 ce 79 62 46 b4 73 3d,ct=7c 1c 69 4d 31 13 72 e3 e0 c4 cd 37 04 ac a7 d0
algo=twofish,mode=cbc,key=14 ac 6c d1 83 35 d5 8c 65 e9 72 39 ea 6d d8 b2 a2 bd d6 36 98 b2 a6 18 eb 93 e8 76 20 5d 42 96,iv=20 83 34 e6 4f cf b4 f5 67 ba 42 fa 1f b3 6d f6,pt=57 01 83 ed ad a3 51 c3 32 49 ab 45 df af c4 e5,ct=25 02 8c 54 6f 8b 88 11 68 aa b9 ca 87 02 38 fb
algo=twofish,mode=cfb,key=0f 7f 0b a5 78 fb bf 89 df d8 fc 46 57 18 41 55,iv=ea e8 f8 6a 89 9a 38 7d e5 f7 d6 4e fb 01 6b f2,pt=9e 4c 9f dc 80,ct=e7 46 9c 62 c9
algo=twofish,mode=cfb,key=0f 7f 0b a5 78 fb bf 89 df d8 fc 46 57 18 41 55,iv=ea e8 f8 6a 89 9a 38 7d e5 f7 d6 4e fb 01 6b f2,pt=8b b0 58 d4 62 cc 1a a8 48 bd 7a 7f ee 63 e9 62,ct=f2 14 3e 6d d0 5f de 61 34 8b f8 04 c8 bd 86 49
algo=twofish,mode=cfb,key=63 98 4f e2 97 8a 15 15 2f 5a b9 ce 30 94 ce a4 31 72 37 e1 81 64 ad 04,iv=05 13 49 da 79 4b 1f cb bb c4 10 f0 fc 35 71 0c,pt=05 63 ab 93 77,ct=78 c0 60 e0 21
algo=twofish,mode=cfb,key=63 98 4f e2 97 8a 15 15 2f 5a b9 ce 30 94 ce a4 31 72 37 e1 81 64 ad 04,iv=05 13 49 da 79 4b 1f cb bb c4 10 f0 fc 35 71 0c,pt=0c 65 85 52 e5 1c 33 a6 b8 ae 98 c3 7a 3e 7f 24,ct=71 12 4e c5 5f 55 97 0b 7f 4c eb ea 4e c7 a6 01
algo=twofish,mode=cfb,key=06 4d 83 c5 59 03 08 8c 04 ad f1 df b0 85 35 55 31 7d 7c 53 c1 c2 98 a2 dd cb 6b f0 03 b4 b0 e0,iv=aa 90 14 9c a6 55 af 1d 0b f6 00 dc 7b 8a 46 8c,pt=fa ca 95 f6 7a,ct=b1 44 4e a8 23
algo=twofish,mode=cfb,key=06 4d 83 c5 59 03 08 8c 04 ad f1 df b0 85 35 55 31 7d 7c 53 c1 c2 98 a2 dd cb 6b f0 03 b4 b0 e0,iv=aa 90 14 9c a6 55 af 1d 0b f6 00 dc 7b 8a 46 8c,pt=58 2d 1b d1 5b f8 03 95 d5 f3 4c 47 84 c0 a4 ba,ct=13 fc c0 cf a8 a4 d4 f5 9f 39 ba ce 76 de cf da
algo=twofish,mode=ctr,key=1b 8d 2b 52 50 7a f9 02 45 54 94 76 62 12 c9 06,iv=db 5b a7 6b bc f9 be 6f 51 8b bd e1 ce 44 2c 7e,pt=2c 7d ee 4a 8e,ct=10 e9 ec 45 e6
algo=twofish,mode=ctr,key=1b 8d 2b 52 50 7a f9 02 45 54 94 76 62 12 c9 06,iv=db 5b a7 6b bc f9 be 6f 51 8b bd e1 ce 44 2c 7e,pt=05 9a 24 5e d0 b4 17 61 fb 16 ed a7 b8 f7 ee 01,ct=39 0e 26 51 b8 9a c1 da 09 1f 14 f2 05 08 95 33
algo=twofish,mode=ctr,key=e1 20 92 71 7a 8c b8 07 d3 d8 60 85 d6 c3 23 c6 e2 f5 42 07 be 96 8e 39,iv=41 e1 3f b5 49 a3 cb 4f 83 6b a6 f8 75 17 4a 83,pt=fa 4f 1e 87 43,ct=87 02 16 73 e9
algo=twofish,mode=ctr,key=e1 20 92 71 7a 8c b8 07 d3 d8 60 85 d6 c3 23 c6 e2 f5 42 07 be 96 8e 39,iv=41 e1 3f b5 49 a3 cb 4f 83 6b a6 f8 75 17 4a 83,pt=6d 88 c9 a0 ed c8 6e 98 d4 a1 1e e5 72 c3 0d 93,ct=10 c5 c1 54 47 66 25 f1 e2 24 a6 1d 09 45 05 5d
algo=twofish,mode=ctr,key=fe f9 8e 62 ed d4 52 59 f6 a3 81 b4 b7 1b b6 bc b1 42 1b af cf f6 c8 f1 03 8c 0d b2 dd 1c e5 1d,iv=9d 7a cb 35 de 14 94 a0 f4 6c 39 63 79 d3 62 1e,pt=d2 3e ec 69 7d,ct=24 a3 b7 15 8a
algo=twofish,mode=ctr,key=fe f9 8e 62 ed d4 52 59 f6 a3 81 b4 b7 1b b6 bc b1 42 1b af cf f6 c8 f1 03 8c 0d b2 dd 1c e5 1d,iv=9d 7a cb 35 de 14 94 a0 f4 6c 39 63 79 d3 62 1e,pt=51 71 5e ac 62 fc 04 1f 26 f9 ba df 88 e6 0d ee,ct=a7 ec 05 d0 95 4c 0d 53 fc 53 7f 8f cb 25 3e fd
algo=twofish,mode=ecb,key=6b d2 51 3a 45 45 07 c9 de bc d8 58 7b 92 08 82,iv=55 8c 06 cb f9 af 18 3b 3c 89 44 1e de f8 b7 00,pt=f2 48 83 05 ed 44 b8 57 06 01 8c d6 ca 8a 3d d8,ct=2e 2c 92 33 d1 40 2d d4 1c 3e 27 b6 d2 0e 12 b3
algo=twofish,mode=ecb,key=9a 6d e5 c8 8f 20 ec b2 05 bd 81 16 b2 c3 9d 4e f6 ce c0 f2 8c 08 5d c8,iv=db 55 cf 9b b4 98 ab a8 7d b1 39 b1 a5 31 f9 c7,pt=89 85 55 f4 62 c7 f8 0b 28 73 f4 46 4c d7 a3 06,ct=fb 5a 5a 6c 76 c4 73 2d c5 5d 35 5f 09 8f 56 cd
algo=twofish,mode=ecb,key=bc 70 aa 12 ba ed 10 1f 9d 01 2d 66 a5 4d 98 9f 0b 2f a5 7c 5d b3 67 9a 2d 27 b4 8c 19 39 ad a0,iv=fa f0 bc 5c 0e a2 c6 cb f2 5c 22 dc 08 e9 fe 2f,pt=75 f4 f5 e2 aa 75 91 ee b6 6c 8b 95 f6 52 1f 70,ct=b5 6d 75 f0 7a 3f 75 4a 65 23 19 9e 4d 11 10 1a
algo=twofish,mode=ncfb,key=a7 6b f1 2c ad 9b ae 92 fa 41 01 1b 3a 63 2d 88,iv=92 c8 a7 3c 99 03 d0 05 44 f0 83 9f 7b 01 f1 0a,pt=d6 00 f9 0b 19,ct=63 a5 b5 c1 b4
algo=twofish,mode=ncfb,key=a7 6b f1 2c ad 9b ae 92 fa 41 01 1b 3a 63 2d 88,iv=92 c8 a7 3c 99 03 d0 05 44 f0 83 9f 7b 01 f1 0a,pt=f0 54 95 7e 8e bb f6 3f c4 c0 6b 2e 89 39 d1 39,ct=45 f1 d9 b4 23 06 87 3e 49 2e 94 f1 1c dc e7 3c
algo=twofish,mode=ncfb,key=ba 5c 02 7b cb a0 c3 71 0d 76 95 f1 04 44 5a a8 2c 8b 7a 1f b3 00 5a fa,iv=12 3d 17 e1 10 d6 7a 0d 99 67 57 f7 63 83 c7 03,pt=74 2c 16 0e 5e,ct=a1 aa 7d 1d 94
algo=twofish,mode=ncfb,key=ba 5c 02 7b cb a0 c3 71 0d 76 95 f1 04 44 5a a8 2c 8b 7a 1f b3 00 5a fa,iv=12 3d 17 e1 10 d6 7a 0d 99 67 57 f7 63 83 c7 03,pt=bc 80 34 81 c6 85 34 79 11 59 d8 ae 1f d4 d8 26,ct=69 06 5f 92 0c 41 0a 0f 13 82 b5 34 0f 8f 4c e0
algo=twofish,mode=ncfb,key=e3 84 49 b5 bd 0e 16 fd 9f 55 d0 0d 6b a0 83 95 8c fc 76 6a e0 43 6a f7 d4 c4 94 2c 6b 72 b4 db,iv=fe 08 93 a2 d4 73 a2 fc 0d 71 9d 18 f8 b1 e7 e3,pt=93 36 ad e4 92,ct=ba 09 d2 b8 c0
algo=twofish,mode=ncfb,key=e3 84 49 b5 bd 0e 16 fd 9f 55 d0 0d 6b a0 83 95 8c fc 76 6a e0 43 6a f7 d4 c4 94 2c 6b 72 b4 db,iv=fe 08 93 a2 d4 73 a2 fc 0d 71 9d 18 f8 b1 e7 e3,pt=25 91 61 9d 7e e3 8c 47 c9 bd f0 f8 da ad 29 c5,ct=0c ae 1e c1 2c 54 05 a0 81 61 cc bb fa c1 e9 98
algo=twofish,mode=nofb,key=45 ef d9 70 42 00 e7 c6 8e 93 98 fb 2a 59 5b 29,iv=cb 1c c0 4d 42 43 dd f2 9b dd db 3b 9f 6b f9 db,pt=b8 d2 46 71 81,ct=05 a5 23 6e 44
algo=twofish,mode=nofb,key=45 ef d9 70 42 00 e7 c6 8e 93 98 fb 2a 59 5b 29,iv=cb 1c c0 4d 42 43 dd f2 9b dd db 3b 9f 6b f9 db,pt=81 00 46 31 2d 57 91 7e 92 a9 fa 78 bb 30 43 6f,ct=3c 77 23 2e e8 95 3b 93 a0 29 41 5a 24 21 78 e2
algo=twofish,mode=nofb,key=90 8e a1 33 dc d4 21 6d 83 b2 14 fc 0d 10 45 39 c1 43 ea 49 c1 a3 3f 69,iv=79 d1 21 34 b1 fc 9c 4b cf 06 b7 57 6f 89 be 9f,pt=c2 d2 2f 9e 9b,ct=e1 8f f5 52 8a
algo=twofish,mode=nofb,key=90 8e a1 33 dc d4 21 6d 83 b2 14 fc 0d 10 45 39 c1 43 ea 49 c1 a3 3f 69,iv=79 d1 21 34 b1 fc 9c 4b cf 06 b7 57 6f 89 be 9f,pt=34 c3 33 09 a1 40 bd de 46 41 f5 42 cd ed 1f 43,ct=17 9e e9 c5 b0 77 cf eb 9f c9 88 ba 15 44 80 81
algo=twofish,mode=nofb,key=48 45 46 b0 0c e8 0f 87 d6 9d 34 09 11 af 64 71 a4 94 ad da c8 2d 48 3e 0b 85 2c 53 07 a8 6b d5,iv=9a 5e bd 48 6d b4 a4 70 1d e6 51 ae 9a 6d 0c 16,pt=47 eb c5 f9 63,ct=19 e4 08 c3 33
algo=twofish,mode=nofb,key=48 45 46 b0 0c e8 0f 87 d6 9d 34 09 11 af 64 71 a4 94 ad da c8 2d 48 3e 0b 85 2c 53 07 a8 6b d5,iv=9a 5e bd 48 6d b4 a4 70 1d e6 51 ae 9a 6d 0c 16,pt=cf 94 77 49 c3 8f 02 f8 07 86 39 eb 6e b1 88 64,ct=91 9b ba 73 93 d1 bd bc e9 1c 33 21 8f 2b 7b a6
algo=twofish,mode=ofb,key=c1 85 36 a9 7c 66 b9 ad 1a 7f b8 a7 52 26 71 50,iv=7a 71 33 ca bd 81 65 6f eb f2 93 9b e7 04 ed 4e,pt=a7 67 d1 b8 8c,ct=3a 17 45 50 dd
algo=twofish,mode=ofb,key=c1 85 36 a9 7c 66 b9 ad 1a 7f b8 a7 52 26 71 50,iv=7a 71 33 ca bd 81 65 6f eb f2 93 9b e7 04 ed 4e,pt=67 6d 25 53 f0 1e df 07 6a 06 6b 58 8b 76 84 36,ct=fa 1d b1 bb a1 ff 5d 6f 7a 3f 30 06 eb 34 47 c1
algo=twofish,mode=ofb,key=f3 c3 f3 dd 49 7c e8 7d aa e5 1c 83 38 a3 81 09 a6 b1 60 a9 63 fe 33 69,iv=c6 b3 52 2d 39 69 a4 1a 0c 19 d5 ca ea c1 57 cc,pt=68 6f 10 04 60,ct=28 33 13 03 6c
algo=twofish,mode=ofb,key=f3 c3 f3 dd 49 7c e8 7d aa e5 1c 83 38 a3 81 09 a6 b1 60 a9 63 fe 33 69,iv=c6 b3 52 2d 39 69 a4 1a 0c 19 d5 ca ea c1 57 cc,pt=ae e3 98 ca da 14 34 22 53 e0 fd 6c 91 b0 b6 d0,ct=ee bf 9b cd d6 5c 81 cf 4e 15 52 8a 19 97 96 ee
algo=twofish,mode=ofb,key=2b 71 53 0f 35 60 82 de 4c 88 cf 77 73 3d 47 d1 25 24 7a 63 41 7b 1c a7 fb a8 78 22 bd 95 31 08,iv=34 84 d4 38 f1 ae 7b 5d b7 0f ab ba 59 48 20 5b,pt=b9 3b d3 99 34,ct=b9 c1 f5 e7 3d
algo=twofish,mode=ofb,key=2b 71 53 0f 35 60 82 de 4c 88 cf 77 73 3d 47 d1 25 24 7a 63 41 7b 1c a7 fb a8 78 22 bd 95 31 08,iv=34 84 d4 38 f1 ae 7b 5d b7 0f ab ba 59 48 20 5b,pt=78 ae 6d 5e 86 62 a6 b6 47 7e eb b8 d8 53 e7 09,ct=78 54 4b 20 8f f8 85 b4 5a bf a4 29 ed 00 07 a7
algo=cast-256,mode=cbc,key=ac 4c 84 13 b3 48 e5 4e f4 39 d9 3e 40 ef 7e cc,iv=0d 6e 28 63 25 ca 43 b8 21 63 d5 9a 26 2f ad f8,pt=3a 26 cb f4 9e a0 01 63 f7 72 10 c1 a3 f6 68 81,ct=da d5 2a a3 01 80 e4 7d 3b b3 c4 e3 89 29 99 44
algo=cast-256,mode=cbc,key=87 28 89 f2 78 fd 60 1e 11 b6 89 4e da 60 7d 63 7f c8 d5 77 22 c4 7f fe,iv=96 30 ec 6b f2 f8 88 44 90 fa 44 68 2a 0e b9 f3,pt=cb b6 ea 8b 56 6e 03 24 a4 db 3d 09 f1 99 dd 6d,ct=ce bd 73 00 01 4d 14 24 a0 ea fd f8 6b ba 09 2b
algo=cast-256,mode=cbc,key=d1 e1 54 dc 28 9c f2 63 46 08 be 6b 39 5c 3b 5c f4 c8 4a 28 b7 c5 17 3a 46 9a d5 26 2f c2 f8 a8,iv=a0 38 17 5e 70 19 ba 58 b0 73 2e c0 d2 97 b0 77,pt=a3 09 3e fc 2b 59 db 80 12 a6 53 d8 82 ed 86 31,ct=ea cf d4 28 cb 51 6b c5 7f bd f3 cc 0e d3 c7 95
algo=cast-256,mode=cfb,key=c7 13 ed df 06 16 e5 4a 96 99 18 c0 4e be bc 0a,iv=87 ad 34 e0 b9 9a 8e 14 99 2f ce 93 e2 60 e0 eb,pt=eb f3 48 b5 53,ct=83 4a 2f 4d 6c
algo=cast-256,mode=cfb,key=c7 13 ed df 06 16 e5 4a 96 99 18 c0 4e be bc 0a,iv=87 ad 34 e0 b9 9a 8e 14 99 2f ce 93 e2 60 e0 eb,pt=4c 3a a9 28 3b 3d 38 1c 85 24 85 00 46 98 8d ca,ct=24 be e7 19 da 39 bf 3a b9 88 34 1b 8c 1c 92 de
algo=cast-256,mode=cfb,key=a8 f4 50 88 83 43 c6 86 83 3a 8c 26 fb f5 c3 25 60 8e b0 01 be 31 2c 5a,iv=e9 69 13 c4 32 8c b6 1c da e6 00 c3 df bd eb f1,pt=10 dc e3 92 6d,ct=29 0b 2c 69 91
algo=cast-256,mode=cfb,key=a8 f4 50 88 83 43 c6 86 83 3a 8c 26 fb f5 c3 25 60 8e b0 01 be 31 2c 5a,iv=e9 69 13 c4 32 8c b6 1c da e6 00 c3 df bd eb f1,pt=3e aa b6 a1 9a c2 72 fa 54 b6 24 ce 8b cb fb e4,ct=07 76 8a e6 c9 a5 c9 56 ae 69 35 d6 35 5b f3 0e
algo=cast-256,mode=cfb,key=64 fd 51 75 91 a8 d5 56 c5 91 30 ae 59 ef 61 bf 0c 0e f0 00 1d 3c ad 62 ab b2 38 2d 35 a1 40 9f,iv=18 9e ea 66 a7 7d b2 c1 fb 5f 6f fc 65 4b 69 28,pt=02 95 38 3e 30,ct=68 67 5b fa 0c
algo=cast-256,mode=cfb,key=64 fd 51 75 91 a8 d5 56 c5 91 30 ae 59 ef 61 bf 0c 0e f0 00 1d 3c ad 62 ab b2 38 2d 35 a1 40 9f,iv=18 9e ea 66 a7 7d b2 c1 fb 5f 6f fc 65 4b 69 28,pt=9d 31 93 a7 65 75 5a 4e 60 e4 75 0e 65 02 8f fd,ct=f7 90 62 19 c4 7a 97 63 ca 28 db 60 dc d1 38 b6
algo=cast-256,mode=ctr,key=66 db 9c 35 01 87 c4 48 6d 32 ac 28 78 3b fb 54,iv=17 bc 16 b5 4c 83 d1 6a bb e5 0e d1 70 51 2b 17,pt=ad 57 37 95 80,ct=0d 43 6f 3a 5e
algo=cast-256,mode=ctr,key=66 db 9c 35 01 87 c4 48 6d 32 ac 28 78 3b fb 54,iv=17 bc 16 b5 4c 83 d1 6a bb e5 0e d1 70 51 2b 17,pt=e3 e4 59 1d f5 3f bf 17 52 13 9e f2 6d b4 09 a5,ct=43 f0 01 b2 2b 0f 42 b4 20 6b ba 2b 26 21 23 65
algo=cast-256,mode=ctr,key=28 e7 77 cf 1b b1 23 42 07 c4 26 c3 01 db 32 8b 5d 75 0d 9f 22 58 b2 20,iv=e2 c8 a7 59 6a 00 2e 15 ba f4 47 9f 20 18 e9 9a,pt=d7 44 fc a5 b9,ct=c2 92 28 fb 8e
algo=cast-256,mode=ctr,key=28 e7 77 cf 1b b1 23 42 07 c4 26 c3 01 db 32 8b 5d 75 0d 9f 22 58 b2 20,iv=e2 c8 a7 59 6a 00 2e 15 ba f4 47 9f 20 18 e9 9a,pt=52 ae 2e 77 9f 1a 2c ca 99 27 c7 4d 58 9f f1 ac,ct=47 78 fa 29 a8 b9 61 f3 6c a1 84 4b c9 f8 62 57
algo=cast-256,mode=ctr,key=74 d4 08 52 78 6d 15 7a 7a 88 a5 e9 91 6b 5b e9 47 5d 6c 88 a4 25 14 97 f2 b7 86 e2 4a 1c e2 5e,iv=ca 67 36 0b ad e0 f9 6e 72 12 ef f8 4c 93 19 dc,pt=1f 5f 55 4e a1,ct=8f 61 1b 34 91
algo=cast-256,mode=ctr,key=74 d4 08 52 78 6d 15 7a 7a 88 a5 e9 91 6b 5b e9 47 5d 6c 88 a4 25 14 97 f2 b7 86 e2 4a 1c e2 5e,iv=ca 67 36 0b ad e0 f9 6e 72 12 ef f8 4c 93 19 dc,pt=88 2e ad d2 c6 e1 64 2b 0b af 59 e5 d6 da fe 17,ct=18 10 e3 a8 f6 33 22 7f c8 bd 73 5b d5 54 c7 b4
algo=cast-256,mode=ecb,key=00 70 17 15 e1 a9 4d 15 af 72 78 a4 4a fc 66 84,iv=a2 fa 11 d2 70 cf 90 12 68 6d 34 e6 30 13 63 7d,pt=bb f9 f2 be 3c d0 29 c6 e4 30 b5 3e 0a fb 70 aa,ct=69 e7 7b 36 31 db 54 6f 57 13 74 f7 b2 9c 46 18
algo=cast-256,mode=ecb,key=18 2e 76 13 dd 73 ed 71 ed 55 e5 af 8d 2e ac 46 1f e2 46 af 77 08 77 b7,iv=51 9b f4 85 17 b0 46 f7 49 2d e8 5c df 4a f6 1b,pt=d4 0e 83 0f 08 d1 76 ea 18 43 60 0b 60 f3 08 66,ct=68 13 ef bf 0c a4 17 bd a5 ce 70 df f0 d1 11 84
algo=cast-256,mode=ecb,key=4b 4d 40 bc 46 11 c8 c1 79 5f 07 a0 13 67 39 d6 59 12 29 7e a3 61 91 cb e7 65 05 0e 17 1a 55 e2,iv=fb a1 4e 25 a9 8f 7c ea c9 90 00 4e d2 b4 f8 5b,pt=79 81 0e 3f 8f 9a a8 c5 04 a0 72 51 4c 6a 25 33,ct=58 88 5c 27 11 34 c6 5a cf e6 ba 35 f3 c7 53 32
algo=cast-256,mode=ncfb,key=26 de 68 96 4f 99 27 35 0a 5d 1a 07 b9 8b 1b 4b,iv=a3 b4 c7 17 dc e8 81 4c 38 fd 08 e1 90 96 7e ad,pt=c1 e8 d4 f9 2d,ct=41 41 92 a5 b2
algo=cast-256,mode=ncfb,key=26 de 68 96 4f 99 27 35 0a 5d 1a 07 b9 8b 1b 4b,iv=a3 b4 c7 17 dc e8 81 4c 38 fd 08 e1 90 96 7e ad,pt=c7 7a 9f 6c 75 b0 4b 61 4f 2f b7 cb 5f 3e b8 c6,ct=47 d3 d9 30 ea da f4 cb 3a 13 21 74 06 f2 ed 25
algo=cast-256,mode=ncfb,key=b1 11 43 90 a9 f7 07 43 e9 44 92 d1 ab 1b 0d a9 b7 16 e9 f4 ef 63 28 f9,iv=68 95 0c 36 c7 01 43 01 64 01 b9 d2 e5 04 fe a1,pt=93 9b e2 79 7e,ct=71 85 39 d3 3d
algo=cast-256,mode=ncfb,key=b1 11 43 90 a9 f7 07 43 e9 44 92 d1 ab 1b 0d a9 b7 16 e9 f4 ef 63 28 f9,iv=68 95 0c 36 c7 01 43 01 64 01 b9 d2 e5 04 fe a1,pt=96 c5 65 6e 0c c3 75 6b 79 06 48 0a 65 7e 89 81,ct=74 db be c4 4f 6f af 29 c7 38 5a 87 a3 1a ed f8
algo=cast-256,mode=ncfb,key=ac fc bc bf fe 60 08 e6 a6 0e 2e f4 90 7b 0d 6a 15 e5 0e 9f 2c c5 14 1d 17 2c 8d 64 89 8a 68 1b,iv=ca 05 ca 01 7b a3 03 4c 1b 20 18 67 6d 7b 72 39,pt=2d 8c 63 4c a4,ct=a3 b4 ca cf ff
algo=cast-256,mode=ncfb,key=ac fc bc bf fe 60 08 e6 a6 0e 2e f4 90 7b 0d 6a 15 e5 0e 9f 2c c5 14 1d 17 2c 8d 64 89 8a 68 1b,iv=ca 05 ca 01 7b a3 03 4c 1b 20 18 67 6d 7b 72 39,pt=a8 61 45 17 48 a2 5e 5c 89 29 ba 46 e0 2b 15 d0,ct=26 59 ec 94 13 81 87 8a 89 dd 97 51 83 73 28 59
algo=cast-256,mode=nofb,key=22 98 b6 a1 52 9c 18 25 2d c8 bf 79 d8 e3 a2 58,iv=2b 5d f6 56 2e 4e bb 80 12 1c 2f 04 59 75 3e 5a,pt=19 17 e0 82 09,ct=e4 94 8b 1f 31
algo=cast-256,mode=nofb,key=22 98 b6 a1 52 9c 18 25 2d c8 bf 79 d8 e3 a2 58,iv=2b 5d f6 56 2e 4e bb 80 12 1c 2f 04 59 75 3e 5a,pt=fa 90 4f fb ed d3 2d 2c a0 99 55 1a f0 ae 0d 4f,ct=07 13 24 66 d5 87 6c cc 2a 7d cc ff c7 55 a4 c1
algo=cast-256,mode=nofb,key=67 21 93 a3 e8 ee 18 38 b6 ce fd 30 66 d1 4b ef 61 54 22 f1 55 77 87 7c,iv=b1 d1 06 03 63 3c 95 6e 38 71 25 14 7f 89 15 5e,pt=22 4d 95 32 69,ct=27 43 35 1c 48
algo=cast-256,mode=nofb,key=67 21 93 a3 e8 ee 18 38 b6 ce fd 30 66 d1 4b ef 61 54 22 f1 55 77 87 7c,iv=b1 d1 06 03 63 3c 95 6e 38 71 25 14 7f 89 15 5e,pt=9e cd 78 64 29 0b 41 b5 af 9e 4b d6 37 86 17 3c,ct=9b c3 d8 4a 08 2a 4e ef ca a0 13 03 c6 a4 d4 be
algo=cast-256,mode=nofb,key=7e 3a 0a a8 1c 7b 4d 22 0a f7 ad 37 ae d2 31 0a 3d 55 56 7f 7c 4b 4c 06 8e 11 ad b4 e0 a7 a8 1e,iv=68 7b 03 a8 ba ae d5 fd c8 36 52 c0 05 0c 8e 7f,pt=e6 9e 6a 0f 65,ct=ed 8d 5c 7b c6
algo=cast-256,mode=nofb,key=7e 3a 0a a8 1c 7b 4d 22 0a f7 ad 37 ae d2 31 0a 3d 55 56 7f 7c 4b 4c 06 8e 11 ad b4 e0 a7 a8 1e,iv=68 7b 03 a8 ba ae d5 fd c8 36 52 c0 05 0c 8e 7f,pt=1c c9 5c f0 0b eb 3c b4 24 e1 1a e3 56 f3 6c 9d,ct=17 da 6a 84 a8 5b 8f fc 9a ce 76 ce 1f 7d b8 ce
algo=cast-256,mode=ofb,key=83 95 dc 30 64 df 40 30 6c 6f 4b 8b 0a b0 5d d3,iv=ed 5a 12 6b 2f 41 b6 4a 7a 18 f2 f7 02 ce da b0,pt=9b 73 6f f2 f8,ct=b4 4b ad f1 61
algo=cast-256,mode=ofb,key=83 95 dc 30 64 df 40 30 6c 6f 4b 8b 0a b0 5d d3,iv=ed 5a 12 6b 2f 41 b6 4a 7a 18 f2 f7 02 ce da b0,pt=cc 37 17 21 19 64 d9 8e 9d 29 50 29 3f c7 e4 d6,ct=e3 0f d5 22 80 76 08 6d a8 e2 26 63 f5 27 4d 09
algo=cast-256,mode=ofb,key=30 f6 92 01 50 d3 cb b0 24 d1 44 6f 30 a1 2f b0 be e2 da e9 b5 1d 53 df,iv=82 34 ed 01 81 b9 69 36 ed 2a b9 95 65 04 f4 cd,pt=b2 a7 3a 98 11,ct=14 2a 55 30 6c
algo=cast-256,mode=ofb,key=30 f6 92 01 50 d3 cb b0 24 d1 44 6f 30 a1 2f b0 be e2 da e9 b5 1d 53 df,iv=82 34 ed 01 81 b9 69 36 ed 2a b9 95 65 04 f4 cd,pt=91 09 0a 3c c8 8b 95 04 40 f3 5f 57 5e cb ce 3c,ct=37 84 65 94 b5 22 78 6e 88 59 f5 d6 b5 47 9b 34
algo=cast-256,mode=ofb,key=eb a3 d5 6c d7 cf 88 5d 08 91 2e a3 6e 0d e3 cf 8e 30 63 28 bb e0 ee 6f d8 ea 3e 92 b8 c9 82 55,iv=a8 93 ec 77 7a ae 2e 64 b9 c1 ce 05 87 3f b7 54,pt=b7 da 34 a3 bb,ct=43 56 b8 57 ea
algo=cast-256,mode=ofb,key=eb a3 d5 6c d7 cf 88 5d 08 91 2e a3 6e 0d e3 cf 8e 30 63 28 bb e0 ee 6f d8 ea 3e 92 b8 c9 82 55,iv=a8 93 ec 77 7a ae 2e 64 b9 c1 ce 05 87 3f b7 54,pt=71 9a 0f 3a e3 65 68 2b cc 98 56 d4 ee 1d 6f 4d,ct=85 16 83 ce b2 4b 84 38 30 aa 4e 0d c3 56 37 59
algo=loki97,mode=cbc,key=a7 9f f4 d9 e2 81 02 ed a4 3e bc a9 ad df c0 38,iv=ec 57 0e b6 61 93 0e 13 32 1e be 99 ae 01 1c a9,pt=1f 45 d0 14 e3 20 c0 19 ab 93 42 d5 34 01 8d a7,ct=9f 03 3f 27 d8 7c cb 1d fe bd 2a 0c 11 a5 74 bd
algo=loki97,mode=cbc,key=39 71 6c db 47 66 e3 59 20 12 9e 9f d4 0b 5f ed b0 29 ed f3 9f ae 74 a1,iv=4b 15 1a 3d 31 a0 8c ba 99 e9 06 5d 0b 67 38 73,pt=87 1b 8e 1c 0e 33 29 89 88 45 a3 8e 68 a2 fc ca,ct=09 20 df af 9b 65 df ca 7f a8 0a 86 fa a7 2d e4
algo=loki97,mode=cbc,key=6c e7 e8 9e 65 2c d1 52 10 59 a5 fd 01 62 c7 c2 e4 44 c8 c8 73 22 eb 3f e5 be f9 ae f1 42 f8 f5,iv=ba c6 69 eb 89 66 c7 2e 5f 47 15 f9 5b cf d8 fb,pt=7c f5 91 0c 10 22 ad c7 9c d6 07 ad 05 90 b6 50,ct=41 33 b1 59 2f 09 7d b4 f4 16 7f d2 f4 4f 2c c3
algo=loki97,mode=cfb,key=b1 d6 a4 89 12 69 19 c8 34 44 bf ad bd 1f e3 fa,iv=b1 97 01 80 b9 49 60 02 b9 c5 06 93 a6 08 ce a0,pt=c2 53 7b 06 02,ct=df 27 9d 8d fa
algo=loki97,mode=cfb,key=b1 d6 a4 89 12 69 19 c8 34 44 bf ad bd 1f e3 fa,iv=b1 97 01 80 b9 49 60 02 b9 c5 06 93 a6 08 ce a0,pt=05 5a 24 7d 4e 3f 66 49 15 5b a9 94 2c 8a 0f cf,ct=18 9e 6f 39 21 04 d3 98 c0 c8 26 a1 c9 cb fb 47
algo=loki97,mode=cfb,key=d0 8b 5a 10 b4 ee 2e 86 a6 6c 59 cf 9f a1 a5 8f ee ef 25 ab 15 c3 47 af,iv=1b 61 32 d5 6a 3e 13 4d bb a5 ab f2 9d 60 65 b7,pt=51 3c 5b 58 a7,ct=9c 23 7f 3e 92
algo=loki97,mode=cfb,key=d0 8b 5a 10 b4 ee 2e 86 a6 6c 59 cf 9f a1 a5 8f ee ef 25 ab 15 c3 47 af,iv=1b 61 32 d5 6a 3e 13 4d bb a5 ab f2 9d 60 65 b7,pt=96 32 bd ef bc fc 60 87 7e e2 90 90 3d 59 bd 21,ct=5b 2d a2 ae cb 79 97 0a 14 5e 03 e0 71 ae 29 95
algo=loki97,mode=cfb,key=20 8e 07 95 aa c8 e5 40 38 e0 16 6c 20 08 77 ed 66 19 37 5a 2d 88 95 16 91 55 1e 8d 62 b9 b7 c9,iv=dd 84 a7 45 9a 2a 57 e8 99 0d 93 61 35 be 3d ce,pt=b4 9a d0 07 ee,ct=c7 2d 6c 91 c7
algo=loki97,mode=cfb,key=20 8e 07 95 aa c8 e5 40 38 e0 16 6c 20 08 77 ed 66 19 37 5a 2d 88 95 16 91 55 1e 8d 62 b9 b7 c9,iv=dd 84 a7 45 9a 2a 57 e8 99 0d 93 61 35 be 3d ce,pt=9e f9 a7 b5 33 af 20 00 ed 14 80 c8 1f 46 52 0b,ct=ed 8e a3 2c 9e 8c 37 05 c2 8c 6e 06 fc 9e e2 12
algo=loki97,mode=ctr,key=f7 38 b1 e5 05 b6 b3 95 ca 84 4c 4a 07 d6 06 01,iv=ed 6c 4c 21 94 cf 5a 8b 6c 95 df a3 21 14 19 57,pt=ea 09 cc 1a e9,ct=39 7f 1b 98 7c
algo=loki97,mode=ctr,key=f7 38 b1 e5 05 b6 b3 95 ca 84 4c 4a 07 d6 06 01,iv=ed 6c 4c 21 94 cf 5a 8b 6c 95 df a3 21 14 19 57,pt=d2 28 4e 50 d4 13 bd 7e b3 7a a5 06 28 34 04 d1,ct=01 5e 99 d2 41 66 8f fb 24 61 68 1e 51 4b 9f 9c
algo=loki97,mode=ctr,key=37 ae d3 a1 49 38 b8 1e 98 74 f3 87 b6 46 22 23 6a 79 22 b5 ca 0c 9e c3,iv=69 2c b2 e0 0a 67 48 65 42 23 00 be 1a a9 bf f8,pt=0b 55 53 2d ee,ct=fc 90 43 fe aa
algo=loki97,mode=ctr,key=37 ae d3 a1 49 38 b8 1e 98 74 f3 87 b6 46 22 23 6a 79 22 b5 ca 0c 9e c3,iv=69 2c b2 e0 0a 67 48 65 42 23 00 be 1a a9 bf f8,pt=cb 92 02 52 27 78 f7 7b 1f ae 8d 63 43 b3 a0 80,ct=3c 57 12 81 63 12 f2 7b 8e ec 0b f4 72 dd 6d 14
algo=loki97,mode=ctr,key=ba ef 7a 59 ce 1c c4 ab a4 10 30 3a ca f4 89 4e f5 53 53 05 c4 18 8a 6a 87 b1 e3 19 c1 78 ca a3,iv=89 a4 9e ce 2f 9a 48 01 41 a0 70 89 fc 09 d8 f8,pt=91 b7 5c a8 6c,ct=ff 3b 01 cb 69
algo=loki97,mode=ctr,key=ba ef 7a 59 ce 1c c4 ab a4 10 30 3a ca f4 89 4e f5 53 53 05 c4 18 8a 6a 87 b1 e3 19 c1 78 ca a3,iv=89 a4 9e ce 2f 9a 48 01 41 a0 70 89 fc 09 d8 f8,pt=14 23 76 59 39 0f 08 1e 78 b6 e6 b2 f5 22 b3 c7,ct=7a af 2b 3a 3c 9b 25 5b ca 9f d9 c8 7f 9e b0 c1
algo=loki97,mode=ecb,key=4f 6f 5d 03 51 f2 89 96 32 84 14 68 7b b7 4d b8,iv=78 fe 5b 9b 0f 7e 81 9e 8e 7f 00 4f c2 9d 1a 97,pt=20 9e 23 e2 9d a8 10 3b a5 e0 cc 39 2c 25 86 a3,ct=c8 a9 21 92 66 35 b7 a3 74 d9 40 ae 1b f1 32 b7
algo=loki97,mode=ecb,key=4b d1 d4 9c 1c 63 ad 50 22 5a de 13 7b d6 1e 0e fd 3f da e0 a9 68 31 ca,iv=3f 54 f6 d7 3c 3e 67 04 b6 34 db 85 0a ef 12 8b,pt=ab 80 52 e7 46 61 57 4f d7 d5 04 11 79 5b 48 fc,ct=ae 95 c5 86 27 6b 13 ff 8e 62 98 47 58 b1 25 ce
algo=loki97,mode=ecb,key=6d a0 ec 36 24 ba 03 16 3a b1 fd ad 25 e2 98 b2 a7 3b d9 11 db f2 13 56 60 3c 7d a6 12 35 93 a4,iv=6a 4d 5b 87 7d 7a de b7 01 72 e7 21 2d b8 fb c1,pt=88 54 82 bf 9f aa 74 9b 26 b6 f3 6b 00 2f 51 f3,ct=a8 c8 11 9d 7a 6e 1a 00 03 cc 3d 47 f8 a7 3a 63
algo=loki97,mode=ncfb,key=71 00 8c 42 e8 0e 7a 38 f5 3b 47 74 49 7d 95 5c,iv=63 bb ca 69 8c f3 b4 43 18 3d d9 3e 2c 61 c6 63,pt=3e de 65 7a 1b,ct=56 d3 f7 82 50
algo=loki97,mode=ncfb,key=71 00 8c 42 e8 0e 7a 38 f5 3b 47 74 49 7d 95 5c,iv=63 bb ca 69 8c f3 b4 43 18 3d d9 3e 2c 61 c6 63,pt=ae 13 f0 b6 dc 99 0d 54 eb 01 6b 93 e0 65 40 32,ct=c6 1e 62 4e 97 ba f5 9c a1 8f 2b dd e2 6a 8f 64
algo=loki97,mode=ncfb,key=2e a9 9b 30 1b 07 63 ac 3c d9 6c ed cc 73 7f 82 28 b9 cf 96 5d 86 34 50,iv=62 4e 32 e9 f1 2d 39 2f 0b c1 80 4f 43 00 ae e3,pt=28 71 ec d8 a1,ct=e5 32 41 4a 93
algo=loki97,mode=ncfb,key=2e a9 9b 30 1b 07 63 ac 3c d9 6c ed cc 73 7f 82 28 b9 cf 96 5d 86 34 50,iv=62 4e 32 e9 f1 2d 39 2f 0b c1 80 4f 43 00 ae e3,pt=0a 90 c9 cb 83 02 b0 12 cb 06 d2 7e da 54 d9 04,ct=c7 d3 64 59 b1 b9 0e e3 55 42 ab 4b dc f1 95 53
algo=loki97,mode=ncfb,key=e1 67 6e ee 32 ae aa 7a 28 ee 09 81 2f cf b2 3e 7a f5 d9 58 40 4f e9 87 cd b2 1d 4b 58 6e d2 75,iv=c0 e8 71 b6 6f 99 ed e4 42 15 0d 02 34 a4 44 72,pt=87 dc 94 a9 22,ct=1b 6e 17 52 aa
algo=loki97,mode=ncfb,key=e1 67 6e ee 32 ae aa 7a 28 ee 09 81 2f cf b2 3e 7a f5 d9 58 40 4f e9 87 cd b2 1d 4b 58 6e d2 75,iv=c0 e8 71 b6 6f 99 ed e4 42 15 0d 02 34 a4 44 72,pt=79 10 e3 0b 61 01 df cd 0b 80 eb f4 39 ac e9 15,ct=e5 a2 60 f0 e9 7b 2f f1 90 61 f7 29 92 6e cb 99
algo=loki97,mode=nofb,key=e8 71 d6 eb 6a a6 2a 79 9e 5c b9 f5 c3 df 12 fd,iv=85 48 bf bd 4e 30 41 5c 3b 89 78 62 68 57 d9 b0,pt=36 05 5b 94 3f,ct=47 3f b5 df cc
algo=loki97,mode=nofb,key=e8 71 d6 eb 6a a6 2a 79 9e 5c b9 f5 c3 df 12 fd,iv=85 48 bf bd 4e 30 41 5c 3b 89 78 62 68 57 d9 b0,pt=fb 48 2e 58 6b 5d af 18 6c da c6 82 4d 02 42 b3,ct=8a 72 c0 13 98 b4 1f 29 4b 7e 93 8f ba a7 4a 06
algo=loki97,mode=nofb,key=66 1c 53 35 2e 4e 4b b6 49 2f fc 78 c2 fb 69 a8 6b 7e 95 f8 5a 6a 0a 75,iv=bc 7f a7 3e 05 2f ae f5 f0 c3 09 8e 6a a0 48 1b,pt=50 60 03 a9 7d,ct=aa 06 3b b6 0c
algo=loki97,mode=nofb,key=66 1c 53 35 2e 4e 4b b6 49 2f fc 78 c2 fb 69 a8 6b 7e 95 f8 5a 6a 0a 75,iv=bc 7f a7 3e 05 2f ae f5 f0 c3 09 8e 6a a0 48 1b,pt=47 bc be fa 5c fe 23 07 0a 97 0b eb 04 43 7b da,ct=bd da 86 e5 2d 0a 1b c6 6d 7d 31 8d 7e 6f ae 48
algo=loki97,mode=nofb,key=c2 26 96 20 05 00 91 f9 13 21 23 86 9c 9d 1f 39 8c 62 df e7 86 37 41 f9 b5 1d a2 b9 0a ab 0b 79,iv=f8 65 6a 13 3d ce 1a d6 4e fa c5 32 99 f3 15 35,pt=5e 90 78 ce e4,ct=98 27 ed 3d c2
algo=loki97,mode=nofb,key=c2 26 96 20 05 00 91 f9 13 21 23 86 9c 9d 1f 39 8c 62 df e7 86 37 41 f9 b5 1d a2 b9 0a ab 0b 79,iv=f8 65 6a 13 3d ce 1a d6 4e fa c5 32 99 f3 15 35,pt=0e a7 c4 c9 1e ce 54 03 6f 69 4c 9d 09 91 67 49,ct=c8 10 51 3a 38 56 a6 f7 f1 3c 7d f9 4b d7 98 c0
algo=loki97,mode=ofb,key=5a 93 a3 33 5b 8e 99 d7 4e f1 0a 4c a6 d5 00 e8,iv=59 01 9e f0 7d bf 65 1f 61 4c 51 58 08 bd 4b b3,pt=d0 81 87 22 90,ct=da e4 ee de bb
algo=loki97,mode=ofb,key=5a 93 a3 33 5b 8e 99 d7 4e f1 0a 4c a6 d5 00 e8,iv=59 01 9e f0 7d bf 65 1f 61 4c 51 58 08 bd 4b b3,pt=b5 68 ce df bc 55 5a 80 73 6d 53 10 9c a4 f2 bc,ct=bf 0d a7 23 97 97 d5 eb f0 4a 48 46 4b fb 56 15
algo=loki97,mode=ofb,key=3a da 59 7b 9f c4 eb ef 31 67 c0 f3 2b fe e6 e3 9a 05 85 ee 4d 7a b4 b5,iv=55 be 12 dd 09 4f 58 51 37 f9 3e 77 81 11 01 50,pt=10 3b b7 25 cb,ct=a8 33 98 61 8f
algo=loki97,mode=ofb,key=3a da 59 7b 9f c4 eb ef 31 67 c0 f3 2b fe e6 e3 9a 05 85 ee 4d 7a b4 b5,iv=55 be 12 dd 09 4f 58 51 37 f9 3e 77 81 11 01 50,pt=1a bf 2e 23 72 1e f0 a7 ed 23 58 e6 01 a2 d0 89,ct=a2 b7 01 67 36 06 86 76 34 d4 64 b4 50 b5 09 06
algo=loki97,mode=ofb,key=9f 73 91 a1 29 d5 81 a9 9d e2 e7 6a 47 02 c1 e3 ab 01 46 82 2e c3 05 18 9b b9 a7 d8 7b 8c 7d d9,iv=6f 41 bf c1 05 41 a5 cf e1 ba 02 91 a2 96 46 18,pt=e9 d4 c0 dd 92,ct=f4 6a ec 5b 48
algo=loki97,mode=ofb,key=9f 73 91 a1 29 d5 81 a9 9d e2 e7 6a 47 02 c1 e3 ab 01 46 82 2e c3 05 18 9b b9 a7 d8 7b 8c 7d d9,iv=6f 41 bf c1 05 41 a5 cf e1 ba 02 91 a2 96 46 18,pt=93 60 79 d1 40 42 8b 25 59 3e cc 85 a7 a9 c7 2a,ct=8e de 55 57 9a f3 7f e1 5d 19 2a 98 49 e6 97 68
algo=rijndael-192,mode=cbc,key=7f 55 7a 54 d0 97 36 75 2f b5 2d 03 9a 8e 62 34,iv=e2 1e 39 48 dd 4b 7a 37 aa ea 40 c6 91 62 fc 4c e3 9e cf 9e 3d 9d c0 c8,pt=f5 32 c7 82 f7 8b af 80 0e 2b 65 cb a9 dd 26 6b 92 19 08 b8 90 d2 af 9e,ct=ee 21 23 c8 1d 5d cf b6 84 d1 23 ba 68 59 d3 f9 bc e4 8b f1 c5 1e aa b0
algo=rijndael-192,mode=cbc,key=16 77 3e 0b 92 f7 4f f8 60 bf 05 60 6d 55 58 7b 92 26 36 61 3c 3e bf 74,iv=ea 41 f4 8c 3c 98 17 4d 55 e7 2c b8 77 9b fd 33 80 0d 06 1f ce 4b 69 ec,pt=d2 a9 75 22 23 7a af ea f0 31 87 fe 12 92 49 0a 7f 39 ac 57 4d b2 1c b0,ct=92 e8 4c 4e 6b 74 db 8f 7b e3 67 18 f0 e9 ee 69 02 57 38 df 30 74 18 38
algo=rijndael-192,mode=cbc,key=c8 22 53 2d 04 e4 6f 94 2d ed 4f 17 bb e7 5a f3 09 a4 1e 41 de 74 86 3f 52 80 ba 8c 6b a5 57 4c,iv=d4 b5 f0 1a e8 c8 76 48 1e 3c e7 83 46 48 04 c2 7a b6 1c c3 51 19 1d 11,pt=0f d6 4a e3 2f 59 76 2b f0 b9 0b 1e cb f5 d3 c3 7b 67 82 56 e8 e9 d2 0a,ct=86 a2 96 d8 9e f5 df db 93 97 ee 9f c8 8e 62 b6 6e 80 ab f4 20 1f 9b a9
algo=rijndael-192,mode=cfb,key=9d 66 f1 32 23 00 81 f7 21 ea 6a cb f0 cc 15 71,iv=9e 22 32 98 ea 27 85 b4 0f af f1 a4 6b 77 43 81 7c 0e 79 00 d8 88 df 24,pt=79 e7 a5 68 39,ct=68 48 a3 8f 97
algo=rijndael-192,mode=cfb,key=9d 66 f1 32 23 00 81 f7 21 ea 6a cb f0 cc 15 71,iv=9e 22 32 98 ea 27 85 b4 0f af f1 a4 6b 77 43 81 7c 0e 79 00 d8 88 df 24,pt=c2 91 90 a9 ec d3 7f c1 24 b0 70 57 58 e0 d4 e0 d1 8b 97 64 fa de 10 f5,ct=d3 11 41 ca 95 12 a1 dd 87 43 b0 cb 91 9b 37 93 07 51 5d 2e 7d 10 31 0d
algo=rijndael-192,mode=cfb,key=f1 fb f8 08 c6 2e 7b 41 3d b1 a7 b5 ae dc c0 c7 ef 22 a3 49 33 da a4 f0,iv=c6 9b d3 f9 08 c7 ee 46 2f 38 42 fd 37 d8 3f 65 51 d1 36 9d 62 a7 01 64,pt=2b 8b 73 99 21,ct=79 6a 57 ad 2e
algo=rijndael-192,mode=cfb,key=f1 fb f8 08 c6 2e 7b 41 3d b1 a7 b5 ae dc c0 c7 ef 22 a3 49 33 da a4 f0,iv=c6 9b d3 f9 08 c7 ee 46 2f 38 42 fd 37 d8 3f 65 51 d1 36 9d 62 a7 01 64,pt=72 03 2c f8 ec 01 f8 0c ca 4c f3 e9 08 76 35 9c 72 2b e6 6e b4 c8 6b 05,ct=20 e8 80 09 1f 8b 19 cd ca ce 9e 19 24 53 eb 4e dd 01 c0 49 26 8c 06 bb
algo=rijndael-192,mode=cfb,key=9f 3e 4a aa 52 c6 93 f8 bd 58 c5 fc 42 79 30 ab 50 ef 67 35 bc 8b a2 76 7f 76 b8 e3 5f 98 7c 3f,iv=6c b3 f7 f0 77 30 3f 12 74 d6 96 e4 b0 c8 e8 78 2c 44 91 6d a2 9e 43 bc,pt=df c0 de 24 61,ct=d3 60 5f 21 5c
algo=rijndael-192,mode=cfb,key=9f 3e 4a aa 52 c6 93 f8 bd 58 c5 fc 42 79 30 ab 50 ef 67 35 bc 8b a2 76 7f 76 b8 e3 5f 98 7c 3f,iv=6c b3 f7 f0 77 30 3f 12 74 d6 96 e4 b0 c8 e8 78 2c 44 91 6d a2 9e 43 bc,pt=bd 43 9e 28 a5 f3 04 13 04 35 07 41 2f f4 d5 52 06 29 df 8b ee 36 a5 02,ct=b1 5d 5e 15 b2 01 e2 ad ff 49 b8 26 9e ef ee 19 70 56 c4 1e f7 1b 19 86
algo=rijndael-192,mode=ctr,key=0e 07 9b df 7f db 41 1a 5e 2c d4 1d 71 32 1d ee,iv=0d c9 1d af 46 e0 16 3c 7a 52 64 a3 07 90 39 6f 6f 47 2f 30 96 b7 2b 7b,pt=69 23 8b 88 7d,ct=62 19 dd 41 bf
algo=rijndael-192,mode=ctr,key=0e 07 9b df 7f db 41 1a 5e 2c d4 1d 71 32 1d ee,iv=0d c9 1d af 46 e0 16 3c 7a 52 64 a3 07 90 39 6f 6f 47 2f 30 96 b7 2b 7b,pt=31 bb b4 6c e3 de 4a 59 fa 13 27 0d ad a4 af 5a fd fb fc f1 33 99 48 a6,ct=3a 81 e2 a5 21 4e 1f 8a 87 32 0f 07 d6 be f6 9a 46 91 c5 11 44 c5 9b 87
algo=rijndael-192,mode=ctr,key=0d 26 bd 4c 33 40 f1 7b 40 90 3c 15 26 61 66 17 cf eb 54 ea 4d ae b3 4a,iv=0f 80 bb 9d c3 0f ae 97 af 03 8f 39 d3 b2 7b 7e 7e c2 68 75 cb b0 09 32,pt=f3 f4 2a 02 d2,ct=8d 5f 07 9e d8
algo=rijndael-192,mode=ctr,key=0d 26 bd 4c 33 40 f1 7b 40 90 3c 15 26 61 66 17 cf eb 54 ea 4d ae b3 4a,iv=0f 80 bb 9d c3 0f ae 97 af 03 8f 39 d3 b2 7b 7e 7e c2 68 75 cb b0 09 32,pt=22 89 b9 8a 06 1f 01 b0 55 b0 ce 5e 90 45 6b 4c 53 ca 63 03 1c 29 c3 d0,ct=5c 22 94 16 0c a4 6f 56 5c cd c0 19 a2 1f 5f a4 2f c0 d5 b4 77 6e ab b6
algo=rijndael-192,mode=ctr,key=f3 88 e4 72 b9 0e b3 9b 9d b7 98 e0 76 b3 bb df 20 f8 9e 0a cc 74 f2 bc 53 ed 17 c2 88 0a 6b d3,iv=b9 47 e9 06 fb ed 57 c4 f9 91 7a 96 0d b2 71 df e7 9a 6c 2d 50 92 83 4a,pt=ab d3 28 95 76,ct=b7 ee b7 be e6
algo=rijndael-192,mode=ctr,key=f3 88 e4 72 b9 0e b3 9b 9d b7 98 e0 76 b3 bb df 20 f8 9e 0a cc 74 f2 bc 53 ed 17 c2 88 0a 6b d3,iv=b9 47 e9 06 fb ed 57 c4 f9 91 7a 96 0d b2 71 df e7 9a 6c 2d 50 92 83 4a,pt=e5 24 3e eb 21 6d ac 2d 0b f8 99 d3 1e c8 19 11 e6 a1 db a8 fc 0b af 7a,ct=f9 19 a1 c0 b1 8f 91 9d 50 4d 9c 4b 0b a1 20 e7 e9 65 69 62 ae bf a7 9d
algo=rijndael-192,mode=ecb,key=0d c6 e4 c5 c5 32 fb 94 2c 2d 28 f7 fa 70 06 e6,iv=7b df d8 dc 49 09 85 35 77 e5 91 0f 32 c5 e0 d3 50 be 37 1c 70 9d 0e 6d,pt=1f 04 e1 e4 5f 68 80 de b2 e3 0f fc 12 cb 8f 3b a3 03 37 52 9a 2e 7c ed,ct=fb 07 9f 07 50 e4 9e 28 1c ff 6c d3 7f 49 d9 ad 8b fd bf cd d8 d1 67 32
algo=rijndael-192,mode=ecb,key=36 1b 5b 67 20 f9 0c 18 a2 6b e9 ec 66 d8 54 ce 23 4e 2a 7c bb d8 eb ac,iv=65 e1 31 14 a2 ac 48 61 0f 7f 60 f7 37 2e 4e c8 e1 a7 47 e7 55 5e cf 36,pt=88 ac 46 aa 00 1a 94 9b d4 47 98 49 25 52 e4 6c 8b 65 9c b6 6f 33 3d 99,ct=7d 95 71 f7 34 bb f0 dc 7c 86 cc 28 8c 3d 6f eb 95 60 ca 2d 00 e7 8b 40
algo=rijndael-192,mode=ecb,key=94 d9 b7 66 b3 fd 41 8f 24 f9 e9 db d2 78 c7 38 79 89 31 21 3c ef 8f 13 84 b2 e9 21 b9 b8 05 8c,iv=b5 9b 99 f2 f0 01 21 ec e9 6c 83 3d 90 10 fd 0d 2f d1 ce d8 9b 45 27 6b,pt=a2 5e 1d aa 26 2a 29 b0 51 0c 02 90 48 54 ba 0e 3f 49 82 7a 0f d6 f5 5a,ct=bf 8d bd 0e 37 42 6d 5b 10 67 83 50 f1 6f 86 88 a1 4e 93 ad ff 79 9e 4c
algo=rijndael-192,mode=ncfb,key=f7 18 e1 d3 42 45 1a dc da 04 b7 7a 60 f1 b9 da,iv=0f 25 dd 3b a1 2b eb 2d 09 58 58 a8 65 32 55 17 eb 1f 6a 25 68 35 4c e8,pt=cb 8e f4 9f c3,ct=2b 19 86 18 9e
algo=rijndael-192,mode=ncfb,key=f7 18 e1 d3 42 45 1a dc da 04 b7 7a 60 f1 b9 da,iv=0f 25 dd 3b a1 2b eb 2d 09 58 58 a8 65 32 55 17 eb 1f 6a 25 68 35 4c e8,pt=30 8c 30 b6 89 c3 83 f2 02 cb 5e 6c 50 24 ba 3e a0 90 72 c3 6c 8d 22 57,ct=d0 1b 42 31 d4 8f 6d c0 47 23 d8 54 29 99 9f 5b 7a bd d7 67 bb f2 75 77
algo=rijndael-192,mode=ncfb,key=c2 66 fb 3c fa 90 b7 69 16 42 07 80 31 73 f0 9f 87 9b b0 67 14 5a 03 eb,iv=0a 3b 32 c0 6c 95 b1 ec 97 32 b5 2e e7 1e 21 dc 56 cc fc 5c ab d8 80 dd,pt=12 8f f6 46 94,ct=95 f5 0b 8f c8
algo=rijndael-192,mode=ncfb,key=c2 66 fb 3c fa 90 b7 69 16 42 07 80 31 73 f0 9f 87 9b b0 67 14 5a 03 eb,iv=0a 3b 32 c0 6c 95 b1 ec 97 32 b5 2e e7 1e 21 dc 56 cc fc 5c ab d8 80 dd,pt=58 d2 54 5e 76 a3 7f 9a 5a 12 c6 48 c3 56 30 03 0f e6 45 7b 99 1e 11 3a,ct=df a8 a9 97 2a ff 55 ec cb 67 8d 4a f7 b9 51 ce 3b e3 aa 04 dd b6 37 6e
algo=rijndael-192,mode=ncfb,key=9d a0 97 77 99 77 a9 88 f5 d4 30 85 55 a1 12 f5 3b d4 7f db 56 e8 b5 3b 6e 9d 51 80 d6 f3 ec be,iv=22 3c ab 51 f8 b3 c2 2e 1c 84 4a c6 97 d5 f2 8f b8 0a a2 e9 23 c4 e9 26,pt=ee 9b 76 39 42,ct=1c a6 0f 0f 63
algo=rijndael-192,mode=ncfb,key=9d a0 97 77 99 77 a9 88 f5 d4 30 85 55 a1 12 f5 3b d4 7f db 56 e8 b5 3b 6e 9d 51 80 d6 f3 ec be,iv=22 3c ab 51 f8 b3 c2 2e 1c 84 4a c6 97 d5 f2 8f b8 0a a2 e9 23 c4 e9 26,pt=0c a2 fd 60 36 2c 2b f9 b8 5c 78 de 44 5e 4c 3d a1 5c ac 38 39 c3 f1 aa,ct=fe 9f 84 56 17 46 d9 8d d2 89 60 0f ba 10 5e c1 e7 b6 e5 7f 91 97 38 29
algo=rijndael-192,mode=nofb,key=d9 78 1f b5 0e 01 02 1c 73 b3 ca 25 f5 f8 17 67,iv=8b 10 3d 9f 9a f0 20 6a 3d 74 05 64 97 49 56 f3 4d de 9c 6c 77 65 36 a0,pt=93 06 78 41 69,ct=65 d1 a5 0e 95
algo=rijndael-192,mode=nofb,key=d9 78 1f b5 0e 01 02 1c 73 b3 ca 25 f5 f8 17 67,iv=8b 10 3d 9f 9a f0 20 6a 3d 74 05 64 97 49 56 f3 4d de 9c 6c 77 65 36 a0,pt=51 29 34 1d 44 d8 ad 09 c5 3f 22 8c dc 9c b8 fb 61 79 3e e9 b0 46 1b 05,ct=a7 fe e9 52 b8 b9 45 21 ab 0c a2 7b 71 7b 4e c8 a5 9b d5 d6 e3 3a 79 fe
algo=rijndael-192,mode=nofb,key=67 f4 a2 14 09 32 0f 0e d1 65 de 51 62 cc f4 09 57 29 56 1a 1d ac b2 19,iv=a7 8d ac e3 5f 3b 42 51 8d a8 b3 1d 01 a3 ea 77 5e 8a fc 9d ca d3 2a a8,pt=dc 84 c9 c8 66,ct=30 f1 9f 33 af
algo=rijndael-192,mode=nofb,key=67 f4 a2 14 09 32 0f 0e d1 65 de 51 62 cc f4 09 57 29 56 1a 1d ac b2 19,iv=a7 8d ac e3 5f 3b 42 51 8d a8 b3 1d 01 a3 ea 77 5e 8a fc 9d ca d3 2a a8,pt=37 27 75 f0 8b 63 66 fc 15 be fb 61 d7 5f 96 ed 85 02 d8 72 4d 8a ab 06,ct=db 52 23 0b 42 ca 15 09 93 6b 5b 28 1b 9e ab 62 9f 2f 9f 97 48 39 92 25
algo=rijndael-192,mode=nofb,key=f5 fe 46 67 42 50 ba 3d 9c 34 a2 c9 cc 98 79 78 28 eb a9 f5 c8 05 cc 8d 72 15 13 6c 7c 61 9c af,iv=0d dd f2 7c d0 d4 e0 76 e0 69 3d 22 d4 1e b5 dd 72 95 e3 47 5f bd 14 f9,pt=a7 96 b8 38 89,ct=35 7b 6e 07 76
algo=rijndael-192,mode=nofb,key=f5 fe 46 67 42 50 ba 3d 9c 34 a2 c9 cc 98 79 78 28 eb a9 f5 c8 05 cc 8d 72 15 13 6c 7c 61 9c af,iv=0d dd f2 7c d0 d4 e0 76 e0 69 3d 22 d4 1e b5 dd 72 95 e3 47 5f bd 14 f9,pt=71 4e a6 47 a2 ee ca d4 c4 c0 17 f8 83 24 a0 be df 47 0c d0 21 55 db ce,ct=e3 a3 70 78 5d 76 b4 10 3f 13 ce 41 0f 20 b2 f6 04 e5 fa 81 0e bc db 23
algo=rijndael-192,mode=ofb,key=dc d0 66 0e ae a0 ee 00 22 3e ef 24 e3 c7 65 ea,iv=41 eb 8d bc 56 75 29 db d1 c3 6f df 8b ef 3a 90 7f 77 7a 27 a8 71 df 61,pt=73 74 df 65 34,ct=98 6b 7c 4b 23
algo=rijndael-192,mode=ofb,key=dc d0 66 0e ae a0 ee 00 22 3e ef 24 e3 c7 65 ea,iv=41 eb 8d bc 56 75 29 db d1 c3 6f df 8b ef 3a 90 7f 77 7a 27 a8 71 df 61,pt=9e 0b f8 b4 a2 cc e6 5d ce 0a ed d8 54 31 1f 9a 6b a7 25 b7 f8 c7 50 3f,ct=75 14 5b 9a b5 ff d3 31 6d 4b 43 dd 2d dd 05 01 48 fc e1 e0 eb 9b f4 19
algo=rijndael-192,mode=ofb,key=ab 89 ec 4e 04 f7 7d f3 0a 02 79 2e 2e bf b8 6a 4a 60 97 27 a8 6a c8 e1,iv=a8 b4 1b c7 27 dc d9 58 bf fc cb 87 9c 0a f1 24 15 f2 62 1e 6a 9a b0 fd,pt=be 1d 71 8b 44,ct=e4 10 d9 18 89
algo=rijndael-192,mode=ofb,key=ab 89 ec 4e 04 f7 7d f3 0a 02 79 2e 2e bf b8 6a 4a 60 97 27 a8 6a c8 e1,iv=a8 b4 1b c7 27 dc d9 58 bf fc cb 87 9c 0a f1 24 15 f2 62 1e 6a 9a b0 fd,pt=d0 e7 09 76 1b e5 f5 81 75 81 94 98 2e 2e 21 a7 10 3f b8 e7 64 06 df fa,ct=8a ea a1 e5 d6 12 61 e3 1b d1 2f 71 71 2b 99 9e 20 07 eb d8 ce b6 9a 80
algo=rijndael-192,mode=ofb,key=8d d9 c3 bd 3c 40 3a 95 60 1d ce 36 5f f1 71 fc 4c b9 57 31 b4 c8 33 80 48 ad f5 8c 2f 85 9b bb,iv=4c 38 b2 d9 ae e2 83 60 83 a7 5e df c6 8f cf 2f 01 55 a4 a0 73 44 1a 34,pt=08 9e 55 53 8c,ct=95 71 b0 7c 7d
algo=rijndael-192,mode=ofb,key=8d d9 c3 bd 3c 40 3a 95 60 1d ce 36 5f f1 71 fc 4c b9 57 31 b4 c8 33 80 48 ad f5 8c 2f 85 9b bb,iv=4c 38 b2 d9 ae e2 83 60 83 a7 5e df c6 8f cf 2f 01 55 a4 a0 73 44 1a 34,pt=49 fe d6 f8 c8 55 a8 68 5a 07 fc 37 20 5c ed 1c 1d 9f 77 a1 02 6d 36 b3,ct=d4 11 33 d7 39 e9 00 dd 3e d4 22 cc 47 90 83 7a ab 99 f2 c3 c6 22 e5 be
algo=saferplus,mode=cbc,key=0a 47 54 d2 dd 67 5e 2e 02 48 15 ec a0 b2 01 21,iv=88 d5 e0 ac 6f 44 a0 b8 fe 8b 96 4e 24 b8 04 2c,pt=3f c3 e1 b2 23 d9 d7 9d 60 07 3d 0c 11 00 e6 7e,ct=95 74 12 3e af 7a 8a dc 25 46 dd f6 00 cd c6 51
algo=saferplus,mode=cbc,key=84 26 60 db 96 2c 7d 88 3d 7c 6c ca da 39 85 f1 e3 dc 45 47 e4 52 c3 39,iv=35 6c 68 ca 71 77 d9 1e e0 2b 6c a7 ec b6 59 6b,pt=29 4e 8e 44 2f fd 2e 8f 54 6d ea 29 79 5e a8 52,ct=2a 70 a5 c5 96 6a 4d f7 d3 30 48 9c bf 53 be 35
algo=saferplus,mode=cbc,key=13 7b a5 97 3d bc f3 c7 75 b7 5f 51 82 8c f6 86 fc b1 66 33 76 0e 81 39 6e 82 ac cc 56 56 de a6,iv=19 61 d0 d3 9f fd 0b ea c7 39 86 54 0f db d1 38,pt=a5 30 39 aa 39 0e f1 0e aa 85 65 ee 4b 51 d5 ee,ct=2d 8a 62 06 71 5e ec 48 15 fd 4a 5a 02 4c c1 7d
algo=saferplus,mode=cfb,key=b5 50 2c 6d fa aa 5e 70 b5 87 e1 15 23 e5 68 0e,iv=0c bc b7 83 c0 6c f7 df 21 bc f1 0a 3a 9a 74 35,pt=9c 70 a1 4d 69,ct=8c 2b b5 60 fe
algo=saferplus,mode=cfb,key=b5 50 2c 6d fa aa 5e 70 b5 87 e1 15 23 e5 68 0e,iv=0c bc b7 83 c0 6c f7 df 21 bc f1 0a 3a 9a 74 35,pt=aa e6 c9 97 76 f1 44 69 94 cb 1d 0f f9 09 80 15,ct=ba 74 81 fc 63 49 af 82 75 24 34 c0 c3 eb 0a de
algo=saferplus,mode=cfb,key=b6 31 45 64 08 ee b5 77 66 50 da ce d3 d1 18 b1 c1 cb 2c 7b 23 3a d4 73,iv=b4 10 9d 87 54 62 12 ac 5a fe 3b 2e 4c 0c 26 1f,pt=75 55 ec 39 de,ct=84 a7 3f be 7d
algo=saferplus,mode=cfb,key=b6 31 45 64 08 ee b5 77 66 50 da ce d3 d1 18 b1 c1 cb 2c 7b 23 3a d4 73,iv=b4 10 9d 87 54 62 12 ac 5a fe 3b 2e 4c 0c 26 1f,pt=86 6a 4c 27 a3 35 43 3a 9f dc 70 96 c4 89 60 25,ct=77 d3 6a cb 7c e5 cb 99 20 5e 46 0c c6 cd 88 1b
algo=saferplus,mode=cfb,key=61 13 82 b6 05 57 97 f6 4a 60 a8 03 06 5a e1 77 b0 d9 28 89 7c ae 95 fe 90 e8 95 4d a2 11 b4 90,iv=e9 80 01 b9 08 0c 1c d3 30 6d e8 79 fd 7a 78 56,pt=db 72 f0 de 78,ct=ab b2 7f 0e e3
algo=saferplus,mode=cfb,key=61 13 82 b6 05 57 97 f6 4a 60 a8 03 06 5a e1 77 b0 d9 28 89 7c ae 95 fe 90 e8 95 4d a2 11 b4 90,iv=e9 80 01 b9 08 0c 1c d3 30 6d e8 79 fd 7a 78 56,pt=a8 a4 a3 9d 92 cb af a4 84 73 69 dc df 43 0b ef,ct=d8 90 57 c0 d8 9e 94 c2 c2 b6 af 7e 4f 37 e1 4b
algo=saferplus,mode=ctr,key=be c6 07 76 67 10 d5 48 89 ac 9e c0 28 f1 10 d4,iv=9d 60 02 d5 15 a2 4b 2f 6a 13 9b 17 da 3c 57 6e,pt=11 0b ae a8 cb,ct=b4 4e 09 85 92
algo=saferplus,mode=ctr,key=be c6 07 76 67 10 d5 48 89 ac 9e c0 28 f1 10 d4,iv=9d 60 02 d5 15 a2 4b 2f 6a 13 9b 17 da 3c 57 6e,pt=2b 4f ee 76 e2 42 63 b9 18 02 d0 0c 9a 4e 4f 8b,ct=8e 0a 49 5b bb 08 ad b1 56 7f fb c3 09 71 ef af
algo=saferplus,mode=ctr,key=f7 d2 af 36 d3 a6 57 84 30 2c cb f7 d0 b0 3d ab 9c ae 56 98 a2 ad 4a 7d,iv=8d 6a 01 1f 91 1f 65 2a e6 88 4e 19 0c 9e 67 d9,pt=15 f5 59 09 26,ct=59 02 cf 7d b6
algo=saferplus,mode=ctr,key=f7 d2 af 36 d3 a6 57 84 30 2c cb f7 d0 b0 3d ab 9c ae 56 98 a2 ad 4a 7d,iv=8d 6a 01 1f 91 1f 65 2a e6 88 4e 19 0c 9e 67 d9,pt=35 9b 24 14 e3 db ca 5b 39 4e aa 78 10 7d c9 70,ct=79 6c b2 60 73 c8 ae 6a 77 64 16 a6 b9 9a ca 73
algo=saferplus,mode=ctr,key=6d 35 14 66 1e 1e 7d 04 2d 2b e4 4a 94 05 8e 1f 3d a1 a5 80 55 3b 59 fb e8 79 88 4d d0 7e ef 32,iv=f7 be 40 31 89 51 9a d9 2f f4 21 2f fe 94 da 6a,pt=f2 14 99 86 60,ct=c2 09 50 75 c8
algo=saferplus,mode=ctr,key=6d 35 14 66 1e 1e 7d 04 2d 2b e4 4a 94 05 8e 1f 3d a1 a5 80 55 3b 59 fb e8 79 88 4d d0 7e ef 32,iv=f7 be 40 31 89 51 9a d9 2f f4 21 2f fe 94 da 6a,pt=31 61 c9 f0 79 17 47 10 d9 07 7a 8d 4c f1 64 60,ct=01 7c 00 03 d1 32 3e 0e 54 c9 28 7c a8 da 18 62
algo=saferplus,mode=ecb,key=f3 af f9 44 ba 86 14 93 0c 5d 08 16 8b c9 e8 9e,iv=ef 09 0e 86 31 a1 79 f6 e2 bc d7 c1 81 36 5c 1c,pt=c5 0f 6a a7 f8 b5 16 4f 1f 7a 59 cd 15 0f 76 d5,ct=9f e9 fe bc 1a f6 af 81 85 86 fc bd a2 8e e0 74
algo=saferplus,mode=ecb,key=c9 fb 0e 34 1b f0 8f a6 06 4f df 08 97 e6 f3 2e 3b 24 54 13 1a 7f 58 af,iv=35 fe bd bb 67 d2 08 22 7c b7 ae df b2 20 5d a8,pt=da a4 4c 0c 53 e8 2c 0c 0a 1e 48 38 96 45 05 da,ct=66 bb 62 92 67 17 72 99 79 e4 ae b8 9a c4 4e be
algo=saferplus,mode=ecb,key=36 a6 23 5b 51 d5 77 42 03 ee 49 23 fb 59 58 ae 2f 0b 79 fb fb 2e 02 17 f9 a0 bf 99 20 da ce fd,iv=c3 d4 17 18 ad c0 8e 5c 67 bd 09 9f 1f 36 70 de,pt=59 64 d3 19 ca 7e 0d 13 33 dd 33 e6 e8 df 3f 92,ct=5d cd 29 7d ef 72 98 c1 78 b8 e0 14 8e e5 73 9c
algo=saferplus,mode=ncfb,key=f2 0e 96 37 3e 44 29 6a 46 96 a3 b6 6c 9e 10 1c,iv=2c ac 4b 99 20 cf 64 61 e5 24 ae e1 12 8e f2 e8,pt=08 f5 b2 c2 86,ct=4d ac f3 f0 df
algo=saferplus,mode=ncfb,key=f2 0e 96 37 3e 44 29 6a 46 96 a3 b6 6c 9e 10 1c,iv=2c ac 4b 99 20 cf 64 61 e5 24 ae e1 12 8e f2 e8,pt=06 68 2d 16 ed 69 15 56 84 d2 f1 69 16 50 10 50,ct=43 31 6c 24 b4 24 bb dd 89 56 8c b3 43 bd 31 e2
algo=saferplus,mode=ncfb,key=06 ae ce b9 90 d7 15 25 7f 1a 19 e8 0a 48 00 e7 0f 5e aa 65 fa 0f 58 90,iv=33 6c 59 de 4d 9b 95 ea 07 2d 48 ac a2 86 10 b7,pt=8c 7c 03 cf d1,ct=8c 19 fa e7 42
algo=saferplus,mode=ncfb,key=06 ae ce b9 90 d7 15 25 7f 1a 19 e8 0a 48 00 e7 0f 5e aa 65 fa 0f 58 90,iv=33 6c 59 de 4d 9b 95 ea 07 2d 48 ac a2 86 10 b7,pt=75 38 ea 92 70 e3 3c 95 3f 7f 43 a3 27 5c 8c 9b,ct=75 5d 13 ba e3 49 a5 dd 9f f4 01 da c6 59 ed 81
algo=saferplus,mode=ncfb,key=29 9b c4 d3 a0 b5 31 48 a9 f2 fb d8 53 17 b0 8f 0c 97 31 27 0a 13 76 4f 79 ad 54 1e 57 73 63 38,iv=5a e5 84 86 5b ca 2b 78 c7 9b ec aa c9 07 6f 95,pt=c1 3a ce 6b 4d,ct=49 3f 61 3c ec
algo=saferplus,mode=ncfb,key=29 9b c4 d3 a0 b5 31 48 a9 f2 fb d8 53 17 b0 8f 0c 97 31 27 0a 13 76 4f 79 ad 54 1e 57 73 63 38,iv=5a e5 84 86 5b ca 2b 78 c7 9b ec aa c9 07 6f 95,pt=6e 4b e6 32 ae 6d 8b 08 75 1f 42 51 36 d1 42 a9,ct=e6 4e 49 65 0f 52 fd 74 59 0a df 89 3e 38 cb 18
algo=saferplus,mode=nofb,key=56 22 1f e0 20 3f dd e8 99 76 7a db 17 77 e4 50,iv=a3 48 40 97 0b fb a3 4c e9 b2 d6 14 28 b6 98 11,pt=89 27 bd 39 15,ct=93 c3 8c 98 5d
algo=saferplus,mode=nofb,key=56 22 1f e0 20 3f dd e8 99 76 7a db 17 77 e4 50,iv=a3 48 40 97 0b fb a3 4c e9 b2 d6 14 28 b6 98 11,pt=9c 6e 82 16 25 bc e7 60 28 8d 75 92 4b 5f 76 1e,ct=86 8a b3 b7 6d f8 e2 50 77 28 1d d1 8f 8c 73 57
algo=saferplus,mode=nofb,key=c4 6e d1 30 d7 da ed ae a3 e2 d5 c3 fe 61 78 20 a9 8d 7c cf 94 43 e4 cf,iv=af 9b 4a be f3 eb c3 c5 7c 9e 18 0e 2e da 91 cb,pt=9e 17 5a 51 fa,ct=b4 42 7e 51 bd
algo=saferplus,mode=nofb,key=c4 6e d1 30 d7 da ed ae a3 e2 d5 c3 fe 61 78 20 a9 8d 7c cf 94 43 e4 cf,iv=af 9b 4a be f3 eb c3 c5 7c 9e 18 0e 2e da 91 cb,pt=51 b5 5c 51 db 1a 4d 36 49 80 5e 9e f8 7c 05 0b,ct=7b e0 78 51 9c ec b2 49 bd 29 aa 7d a4 c0 43 16
algo=saferplus,mode=nofb,key=b2 41 1c e8 35 df 15 75 98 7d ef 1a 87 c7 b0 13 0a dc 05 da 26 ab 8d ce 29 c1 e8 29 f3 60 0d 67,iv=b3 c4 b4 09 0b 44 5f 68 b9 21 7e f9 1d 90 d1 b1,pt=f8 f7 f3 4b 47,ct=80 61 7b 15 b6
algo=saferplus,mode=nofb,key=b2 41 1c e8 35 df 15 75 98 7d ef 1a 87 c7 b0 13 0a dc 05 da 26 ab 8d ce 29 c1 e8 29 f3 60 0d 67,iv=b3 c4 b4 09 0b 44 5f 68 b9 21 7e f9 1d 90 d1 b1,pt=3b ea 46 90 c5 41 69 a5 87 ef c6 32 a4 f3 cc 9f,ct=43 7c ce ce 34 89 82 61 6b 98 8a 66 84 a9 15 20
algo=saferplus,mode=ofb,key=0e 39 a5 1f 3f 0e 38 8a 3c cd bc 81 db 65 8a 97,iv=9d 15 d0 98 ef 31 8d 87 e6 ac 26 48 c2 eb d1 c7,pt=af 18 37 5e 1a,ct=e0 21 13 82 1d
algo=saferplus,mode=ofb,key=0e 39 a5 1f 3f 0e 38 8a 3c cd bc 81 db 65 8a 97,iv=9d 15 d0 98 ef 31 8d 87 e6 ac 26 48 c2 eb d1 c7,pt=cc bc eb 09 a2 58 c1 ac 92 d6 6d 7e b2 f6 40 25,ct=83 85 cf d5 a5 9e c6 b1 e7 91 22 f3 c1 62 b6 77
algo=saferplus,mode=ofb,key=e2 73 c2 0e c4 0c 80 b3 48 a4 aa 7a 75 35 e0 d5 8e d4 60 db 67 db a0 d1,iv=8c 01 3b d6 17 e9 d0 84 3e 21 b7 f3 a3 50 f7 8e,pt=c5 15 97 79 09,ct=39 0e 47 c0 aa
algo=saferplus,mode=ofb,key=e2 73 c2 0e c4 0c 80 b3 48 a4 aa 7a 75 35 e0 d5 8e d4 60 db 67 db a0 d1,iv=8c 01 3b d6 17 e9 d0 84 3e 21 b7 f3 a3 50 f7 8e,pt=f9 27 a4 13 dd 1a 00 7c 8e 9d bb f2 ea be 5a 96,ct=05 3c 74 aa 7e 03 a2 19 a8 f3 ce 30 44 56 f0 5a
algo=saferplus,mode=ofb,key=c1 a4 1b aa b8 30 ce 44 dc 7e d9 b7 0a 2f 8a d7 79 b3 2f ee 8c 5d 3e 3f 89 e9 18 e9 d5 c1 4f fb,iv=07 cf 25 c4 41 d0 7f 87 e4 43 18 1d 63 64 1d ab,pt=29 18 bf a5 6a,ct=54 f0 23 08 2e
algo=saferplus,mode=ofb,key=c1 a4 1b aa b8 30 ce 44 dc 7e d9 b7 0a 2f 8a d7 79 b3 2f ee 8c 5d 3e 3f 89 e9 18 e9 d5 c1 4f fb,iv=07 cf 25 c4 41 d0 7f 87 e4 43 18 1d 63 64 1d ab,pt=fb bc b3 63 43 da e6 f8 f8 59 95 19 32 44 7f e7,ct=86 54 2f ce 07 e8 2d ab 46 33 d9 df 45 c4 ac 9d
algo=wake,mode=stream,key=39 0f d2 16 7d 7b bd 65 cc 29 5b 02 a9 ad 71 ee c2 38 ae 0b 10 b2 c3 de 6b bc 66 f1 71 3d 30 24,iv=,pt=5e b8 6a 45 a6,ct=f7 15 1b ab 1e
algo=wake,mode=stream,key=39 0f d2 16 7d 7b bd 65 cc 29 5b 02 a9 ad 71 ee c2 38 ae 0b 10 b2 c3 de 6b bc 66 f1 71 3d 30 24,iv=,pt=32,ct=9b
algo=des,mode=cbc,key=d5 28 c7 d6 78 22 55 88,iv=35 d0 54 05 fb 60 4c 59,pt=bc 4d b5 07 43 91 0f 02,ct=c0 ce a3 62 47 e3 07 a9
algo=des,mode=cfb,key=10 ab d8 d2 95 03 4e d9,iv=7d 24 89 22 ef 0a 68 01,pt=06 ad 41 2a 71,ct=8e 67 31 d4 00
algo=des,mode=cfb,key=10 ab d8 d2 95 03 4e d9,iv=7d 24 89 22 ef 0a 68 01,pt=74 2c fa ca e0 72 7a de,ct=fc 98 b7 f0 80 8e 11 8b
algo=des,mode=ctr,key=c8 a2 0f fb ad 8d 96 6f,iv=c6 46 7c 32 d5 be 7e 76,pt=38 be 60 e4 97,ct=a3 4a b9 9a 76
algo=des,mode=ctr,key=c8 a2 0f fb ad 8d 96 6f,iv=c6 46 7c 32 d5 be 7e 76,pt=2e 63 1f cc 22 60 5d 4c,ct=b5 97 c6 b2 c3 a5 01 f8
algo=des,mode=ecb,key=95 19 bd 8f c9 5a 87 c2,iv=24 cd d9 9f b9 48 ea 30,pt=12 f5 4b 27 24 d1 d0 d1,ct=3e 89 c3 19 7d ce 6d 4c
algo=des,mode=ncfb,key=63 c8 37 5e 4a 9c 33 ec,iv=4c bd 3e f8 ce f4 d9 51,pt=2e e5 61 89 2e,ct=8b 59 d1 0a 88
algo=des,mode=ncfb,key=63 c8 37 5e 4a 9c 33 ec,iv=4c bd 3e f8 ce f4 d9 51,pt=85 3f df 82 b6 e5 4a 18,ct=20 83 6f 01 10 8c 6f 7e
algo=des,mode=nofb,key=b2 07 95 11 74 c5 ec 7d,iv=5f a6 eb 70 bc fa e6 87,pt=f8 57 fc 24 06,ct=34 db 19 dc 20
algo=des,mode=nofb,key=b2 07 95 11 74 c5 ec 7d,iv=5f a6 eb 70 bc fa e6 87,pt=1b 9d 3d f7 c6 b3 28 df,ct=d7 11 d8 0f e0 28 d6 a1
algo=des,mode=ofb,key=9a 02 24 f3 18 17 94 2f,iv=67 81 48 28 92 10 c1 b3,pt=2d dd f7 64 2f,ct=68 1a f6 2a 80
algo=des,mode=ofb,key=9a 02 24 f3 18 17 94 2f,iv=67 81 48 28 92 10 c1 b3,pt=43 7f 90 c0 83 0d fc ed,ct=06 b8 91 8e 2c c5 1b e0
algo=rijndael-256,mode=cbc,key=95 18 d4 b8 20 9b a7 53 a5 32 62 13 c1 e6 e1 23,iv=10 2b dd 37 9a b9 a9 b0 b9 2c ef 49 97 94 52 6e 46 17 46 f3 51 b9 6c be f5 55 92 63 7b b8 a5 09,pt=14 e9 2e 34 3a 1d 3b fa 69 01 5e b0 a7 91 72 77 f0 58 48 df 48 c9 18 6a 23 94 29 36 53 a5 75 8b,ct=96 6f 88 26 3b da a6 a3 54 74 4e 55 81 3c 5a 0a 54 79 28 b4 62 48 37 13 0a 4c ed 04 4f 71 e8 c7
algo=rijndael-256,mode=cbc,key=1f 39 25 23 56 1d 50 03 c5 90 b3 cc 98 5c 1d 66 7f af 83 80 00 4c 83 7f,iv=58 94 87 05 84 5d 28 79 70 ef 39 a4 8f 17 47 7a be 6d 30 4c 86 e0 b8 79 d7 eb 7c 54 87 2d 4e 26,pt=40 7d f5 d7 78 81 c2 06 84 4b 0f 27 f2 53 9e e9 7b 40 94 4e 82 26 bc 8b 3d 30 0d 70 10 a0 1a 87,ct=10 ab 76 ec 48 08 71 39 15 6c 96 86 d8 83 6e e5 2b 36 c0 89 66 a4 1d 25 f7 3e 46 ab 82 63 e7 14
algo=rijndael-256,mode=cbc,key=75 fe fe a6 33 b1 66 ee f9 8a 90 9f a1 af be 14 ed 0c fd 9e f7 d6 80 7a ca 05 f0 18 a3 1e 2e 90,iv=75 cf 60 09 dc 8d 79 7b 08 71 68 52 fd 45 58 ae d9 30 9d b0 b9 5c b0 cc c5 c6 e3 31 51 a7 83 49,pt=3c ba 1a b8 07 d3 df 95 43 bc 39 f3 ae 1c 36 4c 26 88 e3 b4 ef 9c 9a df cb d1 1b 04 d6 40 bd f0,ct=28 b3 af f7 3f 85 cc 4f a7 87 65 7e cc c2 45 7d 72 58 30 d7 fb b9 08 66 ac c4 39 c4 a2 67 e8 6a
algo=rijndael-256,mode=cfb,key=ea c1 90 21 ef 61 ef ae c8 23 04 77 e4 61 8f 2e,iv=01 b6 02 06 c0 3d 4f 6d 0d e7 30 90 ba 15 54 c6 44 b4 7d 8f 99 2a fb 25 15 c5 24 4a c0 f7 7e 16,pt=ee a1 e9 35 e9,ct=92 dd fc 03 1f
algo=rijndael-256,mode=cfb,key=ea c1 90 21 ef 61 ef ae c8 23 04 77 e4 61 8f 2e,iv=01 b6 02 06 c0 3d 4f 6d 0d e7 30 90 ba 15 54 c6 44 b4 7d 8f 99 2a fb 25 15 c5 24 4a c0 f7 7e 16,pt=24 b7 8e 37 cf da 4e 53 d2 0a f3 3e 31 a9 d0 02 53 bb e7 ae 41 e7 5c 3c ca 26 f2 88 10 90 55 1c,ct=58 3a 18 41 93 cc c6 78 1e 32 ce 4a 4c 08 d1 d5 84 4b ef 3d 69 6c cb bb 56 3c ff 97 e9 8d 05 38
algo=rijndael-256,mode=cfb,key=3c d8 55 f7 96 b6 0c 4d a9 0a d3 bc dd c1 0d af 4d c4 a5 00 d1 47 c1 9e,iv=cc d9 33 82 cc 75 64 fd 46 00 c0 20 16 0a 36 0f 3e 6a c9 8a 3c e9 c4 44 4c d3 22 e5 d8 d0 04 fa,pt=fb 34 d5 b6 b6,ct=20 0a a7 16 3b
algo=rijndael-256,mode=cfb,key=3c d8 55 f7 96 b6 0c 4d a9 0a d3 bc dd c1 0d af 4d c4 a5 00 d1 47 c1 9e,iv=cc d9 33 82 cc 75 64 fd 46 00 c0 20 16 0a 36 0f 3e 6a c9 8a 3c e9 c4 44 4c d3 22 e5 d8 d0 04 fa,pt=0f 04 02 ac 4f 16 21 5c dd f6 53 8c da 68 24 17 a5 5d 3c 93 46 b1 b9 38 94 30 81 44 01 c8 52 c2,ct=d4 09 a4 d4 79 65 f6 09 47 a8 9d a7 17 7a 4e 33 88 1e fd 66 d2 2f 98 21 47 94 80 a3 35 64 9e 4d
algo=rijndael-256,mode=cfb,key=db 06 ac 54 bc a1 3f 18 57 4b c6 ee 64 20 da 37 ac cb 4d ee 3d 5e 46 fb 8b 16 07 c3 6d 0d 8d 6e,iv=89 52 ae f0 01 5d f0 a0 d2 94 24 c3 b1 f7 ca b9 0d d9 f0 f6 f1 3b 3e d8 fb 4b 5e f8 0f 21 80 27,pt=c0 a7 75 51 e9,ct=7d a0 33 19 94
algo=rijndael-256,mode=cfb,key=db 06 ac 54 bc a1 3f 18 57 4b c6 ee 64 20 da 37 ac cb 4d ee 3d 5e 46 fb 8b 16 07 c3 6d 0d 8d 6e,iv=89 52 ae f0 01 5d f0 a0 d2 94 24 c3 b1 f7 ca b9 0d d9 f0 f6 f1 3b 3e d8 fb 4b 5e f8 0f 21 80 27,pt=0d 01 07 2f 24 60 36 68 d3 25 9b 37 7d 88 98 b1 55 9b f4 5a 5b eb 43 2b 39 85 1a 06 b0 95 3d a4,ct=b0 93 14 e9 d5 8f 76 9e 52 a2 af 46 af 18 a3 bd b3 38 51 cd cd df e4 fc f4 c8 92 4a 13 68 f6 e3
algo=rijndael-256,mode=ctr,key=33 d6 bd e3 3c 4d a3 0f b5 52 fa 5c d2 b5 56 09,iv=db 7b 8a 28 b9 06 50 d6 be b5 fe 3e f9 9e 41 6c 79 7f 4e 49 0c 54 27 f7 9c 67 83 b0 25 48 cd a1,pt=e5 ee cf 4f ec,ct=41 8e f8 a0 5f
algo=rijndael-256,mode=ctr,key=33 d6 bd e3 3c 4d a3 0f b5 52 fa 5c d2 b5 56 09,iv=db 7b 8a 28 b9 06 50 d6 be b5 fe 3e f9 9e 41 6c 79 7f 4e 49 0c 54 27 f7 9c 67 83 b0 25 48 cd a1,pt=96 e1 5d 96 fb 4a 4b 39 cf 0d 2e fd e5 9d a7 24 a0 c6 c7 5a 72 8e 08 9b 5f 01 43 67 3c bf 7c 69,ct=32 81 6a 79 48 6d a5 10 2b 48 a7 40 e7 d0 bb 43 e1 c8 41 48 2d 98 6f 98 59 91 2f 28 8e d0 36 c9
algo=rijndael-256,mode=ctr,key=81 7e 73 b5 34 5c 48 70 39 c2 8f 0e bf 4b 78 e1 60 b7 fb f7 14 73 53 f1,iv=21 d9 86 c8 18 24 ee af 55 78 bb 78 ea 13 e2 6d b9 d6 eb c2 b2 92 6f 5c 80 53 08 2b fa 88 70 d8,pt=a5 79 b9 b4 54,ct=2c 88 a2 47 91
algo=rijndael-256,mode=ctr,key=81 7e 73 b5 34 5c 48 70 39 c2 8f 0e bf 4b 78 e1 60 b7 fb f7 14 73 53 f1,iv=21 d9 86 c8 18 24 ee af 55 78 bb 78 ea 13 e2 6d b9 d6 eb c2 b2 92 6f 5c 80 53 08 2b fa 88 70 d8,pt=78 50 1f b5 dd 16 46 29 58 51 1b 6a e4 ba 0d 2b 4a b5 3d 74 1d 73 49 ab 57 e5 61 7c b8 66 7d 81,ct=f1 a1 04 46 18 43 28 5d 6d 14 0d f0 40 f2 d9 f5 3f 0b fc 47 31 19 e1 f5 00 e6 cb 66 06 1b d9 01
algo=rijndael-256,mode=ctr,key=1f 05 02 19 c2 3a 00 d8 1b 62 32 e3 08 de a4 6a 70 ee 1d 77 75 92 48 1c 7f ef 0c 5c 7d 12 b8 08,iv=64 70 52 3f 75 1e b2 41 3d 31 c1 f2 3c 6c 6a 49 c0 6d d3 e3 67 47 4a a8 c9 6f ea 74 3c 9d 7b 36,pt=d0 c9 b5 f2 0a,ct=c7 54 8e 35 e3
algo=rijndael-256,mode=ctr,key=1f 05 02 19 c2 3a 00 d8 1b 62 32 e3 08 de a4 6a 70 ee 1d 77 75 92 48 1c 7f ef 0c 5c 7d 12 b8 08,iv=64 70 52 3f 75 1e b2 41 3d 31 c1 f2 3c 6c 6a 49 c0 6d d3 e3 67 47 4a a8 c9 6f ea 74 3c 9d 7b 36,pt=b3 17 0e ef ee 0d 31 34 51 a4 30 e7 2e 43 fd 1c 46 2d e0 ee 36 5e e9 4c e1 ca be 51 d6 39 91 cc,ct=a4 8a 35 28 07 3d db e5 17 b0 ae e8 e5 68 ea b7 ff 52 2b 68 cd 1c 31 96 87 d0 05 cd 21 02 72 c8
algo=rijndael-256,mode=ecb,key=63 58 7a 00 4c 44 f6 3a 72 b3 c0 c1 0d 1d d3 66,iv=76 ac 9d 8f 2c eb eb 72 e9 a4 30 b0 3a 3e d1 15 e1 a4 05 96 01 9c 45 8e b3 a3 ba 24 b5 1a 90 fa,pt=ad fd 2d 60 41 e4 d6 ac 23 58 f6 ca 07 3b ea f1 34 03 c4 67 2d 8d c1 d2 35 e9 c1 72 09 98 5f c3,ct=e4 23 10 72 a3 5b 84 78 e7 7c a7 9c 05 02 09 0a 17 d7 85 66 dc 9c 8a c1 9b f7 90 91 4e 79 61 a1
algo=rijndael-256,mode=ecb,key=d5 dd 4a b0 f2 de 6c b9 29 86 57 8b 09 21 60 6c 5a 29 a3 b4 9e 29 9d f9,iv=59 fa c7 da 11 bf a7 2e d7 8b 32 47 36 20 3c 82 0b 17 e1 18 9c a1 99 09 ae 53 08 63 2f 7b 88 d4,pt=c9 e1 ba 9a fd 7d 8b 67 f5 f2 ea d2 fb 5d f3 d2 a0 fa a3 92 31 48 98 36 25 3b 09 70 e8 b5 fd 2d,ct=87 ff 94 c9 75 b9 fe 82 83 f0 bf 02 41 79 a2 e7 75 43 c4 92 af 59 96 45 46 89 f2 03 e8 81 01 61
algo=rijndael-256,mode=ecb,key=70 54 5b 4c f9 44 01 9f b5 a7 d4 69 04 e4 fc d7 18 20 f1 7e 5f 92 fd ce e6 71 56 a2 80 e5 d5 a9,iv=63 f5 2d 54 8a b4 12 40 74 b9 cd 58 be 7c 8f b9 cf c1 3c a3 25 d5 d5 66 3b a7 7a 06 b6 36 8f 21,pt=65 11 9d 33 81 c0 4b 2e 8d 6c 75 28 88 ab 73 9a a5 81 b2 b1 de 4d f5 7b d1 48 38 bb 30 c2 37 66,ct=37 11 d1 d3 27 4b c6 fa 5d ce e5 bf d1 81 dc 98 e6 f0 ce e3 fc 50 1e 42 b6 4c 31 58 0e 98 98 91
algo=rijndael-256,mode=ncfb,key=eb dd 62 f6 4b 1f c9 b5 bf f3 d3 7b 54 b8 76 aa,iv=9e eb 8d 74 f0 99 bd 7c f7 3b fe 78 67 31 8f 88 36 bc 09 61 28 09 a6 d4 b1 2a 86 8f 79 39 01 82,pt=cf 68 3e 84 fc,ct=61 d0 4f c0 cb
algo=rijndael-256,mode=ncfb,key=eb dd 62 f6 4b 1f c9 b5 bf f3 d3 7b 54 b8 76 aa,iv=9e eb 8d 74 f0 99 bd 7c f7 3b fe 78 67 31 8f 88 36 bc 09 61 28 09 a6 d4 b1 2a 86 8f 79 39 01 82,pt=36 9e af 5d 20 e1 b6 9d e0 bb 6b 1c d8 0e 3a 10 f4 a6 22 19 08 12 a4 64 86 3e e5 a2 7b a8 33 5d,ct=98 26 de 19 17 94 9f 6a 6c 5b 53 09 ea 85 9f 28 7d 83 a2 67 4c 4a 5a 70 99 67 14 3a 23 a9 e0 0b
algo=rijndael-256,mode=ncfb,key=d4 3c 63 23 0f aa bc 2a 84 68 47 be f3 43 69 d1 4e ea 0e b8 9c 06 90 34,iv=47 19 e0 c2 13 e8 44 b5 1b 17 4e f8 7d 09 63 c7 20 09 09 1f c3 cc ed 58 99 88 e4 c8 77 f4 74 c8,pt=4b 74 67 89 a4,ct=86 4b 98 c8 64
algo=rijndael-256,mode=ncfb,key=d4 3c 63 23 0f aa bc 2a 84 68 47 be f3 43 69 d1 4e ea 0e b8 9c 06 90 34,iv=47 19 e0 c2 13 e8 44 b5 1b 17 4e f8 7d 09 63 c7 20 09 09 1f c3 cc ed 58 99 88 e4 c8 77 f4 74 c8,pt=d4 50 88 68 6c 2e d8 ba 22 0c 86 ea 78 52 76 7b 4a 42 ba 8d db 9f 2d e0 b7 87 bc 12 49 53 67 c3,ct=19 6f 77 29 ac 2a e8 f4 65 ec fa b1 9d 5e 9c ae 11 17 aa 24 05 be 79 25 f2 6b b5 e6 26 ab 09 27
algo=rijndael-256,mode=ncfb,key=e6 d1 eb e5 1b 61 e4 7f a8 df f4 08 a4 16 d6 02 a4 ba a6 ad 1c f3 16 62 84 70 d1 62 12 4e d2 9a,iv=11 72 bc 4e 00 0e ee 0e 02 e8 ef a7 e5 69 84 56 07 59 8f de 9e 25 87 17 3a bd 52 88 18 16 34 d6,pt=01 02 f6 ec 48,ct=f7 a7 7c a3 9a
algo=rijndael-256,mode=ncfb,key=e6 d1 eb e5 1b 61 e4 7f a8 df f4 08 a4 16 d6 02 a4 ba a6 ad 1c f3 16 62 84 70 d1 62 12 4e d2 9a,iv=11 72 bc 4e 00 0e ee 0e 02 e8 ef a7 e5 69 84 56 07 59 8f de 9e 25 87 17 3a bd 52 88 18 16 34 d6,pt=43 10 5b f2 7f ac fa 5b e8 93 9f 82 91 3a 7e 56 22 34 4e 8b e9 db a8 10 b2 53 7f 3c ac 8e 69 3a,ct=b5 b5 d1 bd ad ba 18 20 c0 8b f2 bf ae 78 9a 1b 3d 8e fd 27 7b 89 55 7f ca 9e 9d d8 69 63 dc f7
algo=rijndael-256,mode=nofb,key=ae f2 c1 52 8f 6f 8d ef 51 4a 6d d9 83 14 6f 12,iv=67 42 f5 61 7b 20 b5 9d 08 c6 3a b9 db 5f bc 04 46 33 c7 45 2b 76 72 6f b0 ba 9e f1 32 da aa e6,pt=1b 73 57 0e b4,ct=c5 11 48 9e 5d
algo=rijndael-256,mode=nofb,key=ae f2 c1 52 8f 6f 8d ef 51 4a 6d d9 83 14 6f 12,iv=67 42 f5 61 7b 20 b5 9d 08 c6 3a b9 db 5f bc 04 46 33 c7 45 2b 76 72 6f b0 ba 9e f1 32 da aa e6,pt=1b 7e 20 4d e4 7d 55 58 b3 f4 ee 86 63 71 8a fc 8e d8 38 c7 29 7a 71 23 15 c3 62 02 23 9b cd 5c,ct=c5 1c 3f dd 0d 15 ad 9c 70 5b 37 0b 23 a3 fe 4e 3f 32 fd c3 09 bb a8 0d f7 25 d8 30 ac 7d 30 77
algo=rijndael-256,mode=nofb,key=2f 5f 64 f1 b5 2b af 12 d2 28 a0 a8 34 98 47 06 e0 71 05 0a aa 7a 07 fc,iv=df f8 eb a2 b1 a2 03 19 b8 0c a9 5b 61 20 fc 2f 23 2f c6 66 34 de de 34 6f 3f 4f bf 88 32 d6 94,pt=88 2f de 40 c9,ct=4c 95 83 36 08
algo=rijndael-256,mode=nofb,key=2f 5f 64 f1 b5 2b af 12 d2 28 a0 a8 34 98 47 06 e0 71 05 0a aa 7a 07 fc,iv=df f8 eb a2 b1 a2 03 19 b8 0c a9 5b 61 20 fc 2f 23 2f c6 66 34 de de 34 6f 3f 4f bf 88 32 d6 94,pt=a1 c8 e2 96 f2 81 11 a9 2a 37 bd 62 95 c1 c0 bf 9e 56 4f bf 39 cb d7 e3 f6 93 f5 7b 7a e6 11 08,ct=65 72 bf e0 33 bf a1 7d dc 25 ac 9a 95 c3 e9 aa 1a c9 29 41 1d 09 04 47 80 88 ef 06 53 34 42 12
algo=rijndael-256,mode=nofb,key=12 47 08 1a c7 08 c8 d7 ed 37 a9 68 4a c7 48 83 75 c0 bb 38 4c 80 d2 1b a8 bd d9 fe 96 0a 3b 82,iv=6a 56 49 f1 a3 f4 d9 b4 38 3f 5b fd 8b fe 6f 2a ce 30 88 af 40 ef 5b 6e 28 91 17 47 e5 f2 18 b4,pt=2d de 8c 7b 3f,ct=0b 9b a7 23 e8
algo=rijndael-256,mode=nofb,key=12 47 08 1a c7 08 c8 d7 ed 37 a9 68 4a c7 48 83 75 c0 bb 38 4c 80 d2 1b a8 bd d9 fe 96 0a 3b 82,iv=6a 56 49 f1 a3 f4 d9 b4 38 3f 5b fd 8b fe 6f 2a ce 30 88 af 40 ef 5b 6e 28 91 17 47 e5 f2 18 b4,pt=06 95 00 3f 66 96 44 93 14 5d a2 09 b1 64 ad ef e1 fc 66 01 16 86 4d 68 f0 3c 4c b4 93 9a 11 d4,ct=20 d0 2b 67 b1 b3 05 4b 88 86 21 49 4a 72 27 b6 35 97 30 de 0b ea c8 db 07 fb 11 f2 d8 7c 8f 3d
algo=rijndael-256,mode=ofb,key=42 03 e4 4d 70 05 2c 7d c7 cb 8d 9d d5 d5 d7 66,iv=42 88 7d b8 da d9 0b 32 34 c0 50 5b 65 80 bd 14 96 80 f2 5b 90 f8 81 e7 f2 60 4a d9 40 50 1a 55,pt=9a 92 88 51 dc,ct=1d 14 59 c5 7d
algo=rijndael-256,mode=ofb,key=42 03 e4 4d 70 05 2c 7d c7 cb 8d 9d d5 d5 d7 66,iv=42 88 7d b8 da d9 0b 32 34 c0 50 5b 65 80 bd 14 96 80 f2 5b 90 f8 81 e7 f2 60 4a d9 40 50 1a 55,pt=e9 73 dd be 57 31 6a 4a fc e9 bc 4d ca 1b 15 8f eb 04 d9 8a 16 25 a4 ba a1 ef 69 a4 a0 5b 74 14,ct=6e f5 0c 2a f6 22 63 a8 fb 05 51 04 86 f3 01 de da ba 5d 22 aa 3c 34 73 5a 1c e1 af 6a 81 26 7b
algo=rijndael-256,mode=ofb,key=fd cb 79 92 a3 36 51 c8 80 77 4a d6 e8 23 ce df 23 12 5b 12 21 23 d0 5a,iv=2d 6f fb 73 75 3d ce 2a 7b c9 77 92 50 cb b4 cb 4d cb 4b 78 7c 26 e3 19 18 69 57 16 e2 f1 7e 26,pt=80 7a 9e b9 06,ct=29 40 22 43 04
algo=rijndael-256,mode=ofb,key=fd cb 79 92 a3 36 51 c8 80 77 4a d6 e8 23 ce df 23 12 5b 12 21 23 d0 5a,iv=2d 6f fb 73 75 3d ce 2a 7b c9 77 92 50 cb b4 cb 4d cb 4b 78 7c 26 e3 19 18 69 57 16 e2 f1 7e 26,pt=8a 15 db 9b 0e 12 a7 74 35 c0 43 1d 4d c7 46 f9 8d 05 5d 0f 6b 2b 0c 57 79 06 cc bd a5 09 a3 90,ct=23 2f 67 61 0c 85 8f e4 28 83 8b 95 73 51 2b e0 f2 03 87 64 01 8f fa 08 15 6b b6 fc 93 6e 95 08
algo=rijndael-256,mode=ofb,key=27 38 81 84 68 b7 90 b4 1a 4c 09 ec d1 4d 01 3d 12 f2 25 60 86 81 3f 90 8f ef de 56 4f df cd 58,iv=2b 47 41 69 6a eb f6 b4 7d 4c 91 4e 7d 19 45 11 35 24 f6 fd 1c e3 28 af 44 7f 12 9e 64 db d6 8a,pt=52 7b 66 0d d5,ct=99 ae a2 05 b5
algo=rijndael-256,mode=ofb,key=27 38 81 84 68 b7 90 b4 1a 4c 09 ec d1 4d 01 3d 12 f2 25 60 86 81 3f 90 8f ef de 56 4f df cd 58,iv=2b 47 41 69 6a eb f6 b4 7d 4c 91 4e 7d 19 45 11 35 24 f6 fd 1c e3 28 af 44 7f 12 9e 64 db d6 8a,pt=25 37 3e 8a 0c e8 d9 94 d4 97 0e c3 d8 86 a5 85 87 c5 ec 5c 42 14 b5 5a c9 04 c4 a9 f4 6c 4a 4f,ct=ee e2 fa 82 6c 82 bb 87 33 92 13 33 88 fd 70 94 f6 b0 03 63 5b 47 16 63 71 8e 70 da 1a 74 89 66
algo=serpent,mode=cbc,key=2f 62 bc cf b8 6d 2a b7 7c cd 66 d5 20 bc 50 a6,iv=d7 66 19 5e 33 59 43 da e8 83 bf fe 9f 27 05 eb,pt=e1 fa 1b d9 42 14 cd 42 2b 4f 8b 46 75 2e cf e6,ct=cc ca 4b 72 b4 9c b2 4b 2b 26 5c d7 1e d4 51 99
algo=serpent,mode=cbc,key=83 85 9c 29 c3 a3 98 cd 96 17 0d 1b d9 f4 e9 5c 40 d1 29 20 73 ee db 1d,iv=63 a3 a0 c5 ba 5b 05 46 c9 3d ec c6 6b 79 a2 f2,pt=7a d5 2d d4 bb 12 24 71 22 82 eb bc 06 f2 98 8f,ct=6e 32 36 6a 95 ce c4 12 55 50 6a a1 eb 52 49 41
algo=serpent,mode=cbc,key=1d 1d 58 e4 e4 70 b8 61 4d e2 15 34 ab 26 1d 56 58 36 d1 24 aa d4 ad a0 8a 99 fe 01 29 08 c7 97,iv=db 99 92 11 c0 8c 8a 73 65 31 6b 17 56 6f 80 5e,pt=35 6d 63 7c 52 db 80 ad c3 e4 69 85 13 3d 8d 4a,ct=71 f9 25 dd c6 5c dc f0 27 dd a4 8c 8d 4d de c8
algo=serpent,mode=cfb,key=0a 0c 11 30 29 a3 67 31 cf 35 08 31 b9 e6 15 cf,iv=22 0a 0e 67 bf 4b 11 48 de 81 b1 b6 9a 62 29 64,pt=61 5b a6 49 a3,ct=c0 9d f4 66 0f
algo=serpent,mode=cfb,key=0a 0c 11 30 29 a3 67 31 cf 35 08 31 b9 e6 15 cf,iv=22 0a 0e 67 bf 4b 11 48 de 81 b1 b6 9a 62 29 64,pt=59 b8 25 fd 86 45 16 ca bf f7 76 0c c8 bc e4 5b,ct=f8 8c 3a b5 e2 0a f6 45 f8 cc c3 f9 7a d8 7d 48
algo=serpent,mode=cfb,key=d9 76 a3 70 e6 53 e3 32 c6 5c ed 3d ce 0b 2a 6d 38 af a8 c3 90 ce 1a 42,iv=d1 6a c2 b0 5d 80 a9 10 3c b1 71 06 8b 00 07 e8,pt=76 60 26 a9 42,ct=ec 34 de 49 5d
algo=serpent,mode=cfb,key=d9 76 a3 70 e6 53 e3 32 c6 5c ed 3d ce 0b 2a 6d 38 af a8 c3 90 ce 1a 42,iv=d1 6a c2 b0 5d 80 a9 10 3c b1 71 06 8b 00 07 e8,pt=88 fe bd 4a 76 62 0c 83 ac ad 2c a8 09 72 d3 46,ct=12 59 42 2b 65 13 fa 83 e7 6f 84 f4 e5 79 08 5f
algo=serpent,mode=cfb,key=64 dc 41 2a bb 36 ce bf bf 57 16 54 df 65 7a 34 fd 1e f4 f9 db b6 47 64 eb 3e d3 9f 91 62 6a 59,iv=c8 53 55 1c 26 42 57 22 05 7b 3d 44 a0 ae 5a 48,pt=9c a8 13 34 96,ct=e0 90 01 52 d0
algo=serpent,mode=cfb,key=64 dc 41 2a bb 36 ce bf bf 57 16 54 df 65 7a 34 fd 1e f4 f9 db b6 47 64 eb 3e d3 9f 91 62 6a 59,iv=c8 53 55 1c 26 42 57 22 05 7b 3d 44 a0 ae 5a 48,pt=d4 9e c7 1d a4 21 c1 41 f6 b5 d8 a0 2f 44 83 29,ct=a8 0e e6 7a a3 a7 8c 4d 9b 2a 12 5e 02 a5 0c 75
algo=serpent,mode=ctr,key=65 53 44 a2 ce 09 53 c1 8d 15 ab b8 cb 74 47 39,iv=af 77 0e f7 d4 58 e6 06 1b d3 bb fc 69 9d df 96,pt=d7 fe 15 4f 20,ct=00 f8 4b b0 70
algo=serpent,mode=ctr,key=65 53 44 a2 ce 09 53 c1 8d 15 ab b8 cb 74 47 39,iv=af 77 0e f7 d4 58 e6 06 1b d3 bb fc 69 9d df 96,pt=ed 7a f9 d3 86 c5 37 2b 4f de 49 72 cb 95 c9 50,ct=3a 7c a7 2c d6 93 4b a6 41 9a 52 e1 c9 95 4e b2
algo=serpent,mode=ctr,key=bb ac f3 51 39 7c 76 b7 99 4e 35 d6 89 85 16 7a ea 61 69 a6 c4 d9 16 e8,iv=70 bc 03 e2 cf 70 14 e4 8c b5 86 5d a1 16 f2 60,pt=a6 fc 0d 72 17,ct=c2 4a 66 8b fa
algo=serpent,mode=ctr,key=bb ac f3 51 39 7c 76 b7 99 4e 35 d6 89 85 16 7a ea 61 69 a6 c4 d9 16 e8,iv=70 bc 03 e2 cf 70 14 e4 8c b5 86 5d a1 16 f2 60,pt=ec 41 72 ea bc 69 5e f9 f7 87 df b9 8e 40 44 68,ct=88 f7 19 13 51 d7 40 21 38 51 28 51 f2 1e 4a c1
algo=serpent,mode=ctr,key=16 e3 28 ef b4 2a 01 f2 97 3e 6a fa 16 12 17 cf a3 42 77 49 ab ea bf 67 cc 2c 74 e4 7e 13 23 f7,iv=8d 63 3f 30 c7 8f 4e 88 d0 fe bc a0 88 bd 49 81,pt=61 11 ac f7 aa,ct=ad 75 43 57 ac
algo=serpent,mode=ctr,key=16 e3 28 ef b4 2a 01 f2 97 3e 6a fa 16 12 17 cf a3 42 77 49 ab ea bf 67 cc 2c 74 e4 7e 13 23 f7,iv=8d 63 3f 30 c7 8f 4e 88 d0 fe bc a0 88 bd 49 81,pt=e0 0a 23 d7 e1 92 00 e8 7b 9b f1 9d 2a 68 e2 9f,ct=2c 6e cc 77 e7 61 9e b6 95 be b7 d3 03 df 58 07
algo=serpent,mode=ecb,key=42 0d 7b a5 86 98 86 4b 10 12 50 d5 80 c2 c1 91,iv=2b 54 02 6f b2 50 30 c0 d2 94 cb 6a bb c5 70 f4,pt=fe 18 87 7b aa 00 00 11 59 33 1e 91 c8 31 2f 50,ct=95 6b 20 5a 18 22 6d 2d 9e e9 a4 e7 55 95 9d 04
algo=serpent,mode=ecb,key=b3 36 23 59 73 b6 25 c5 f2 78 c3 c1 95 9e 1b 30 7a ca 33 3a ce 3e bd bb,iv=66 9e 89 46 2e 05 3e b5 1a 31 93 6c b9 a9 25 98,pt=26 25 52 ca 36 92 85 55 92 1f 32 1f c9 ad 70 49,ct=b6 53 22 52 59 10 8f 1f e8 e4 b2 ba 45 f6 be c2
algo=serpent,mode=ecb,key=75 ee 5a cf 23 68 e9 25 42 0a 54 6a 23 51 71 aa cf 85 c5 f6 25 2c 3e 6b 4c ee 1a e8 b2 38 3e 90,iv=cd 41 7e 3f b5 e7 37 b9 f4 56 52 44 0b f1 b4 f9,pt=a6 7a 15 0e 03 c5 cf fc 6a 02 b7 0a bf 15 4b c2,ct=1b 14 be 1c 52 f0 a1 84 c8 63 c1 64 0b 71 2c 43
algo=serpent,mode=ncfb,key=84 79 4b 09 07 45 95 ee ec b3 5a d9 f7 1d a6 53,iv=1a 81 57 67 be dc fc 7c de db 91 69 3b bf 54 1b,pt=db 6c ef e8 ac,ct=a5 ca 75 54 67
algo=serpent,mode=ncfb,key=84 79 4b 09 07 45 95 ee ec b3 5a d9 f7 1d a6 53,iv=1a 81 57 67 be dc fc 7c de db 91 69 3b bf 54 1b,pt=92 f0 53 7b fc c0 55 65 2b d5 03 43 a4 9c f9 55,ct=ec 56 c9 c7 37 99 ad 49 91 aa d7 67 84 98 fb 69
algo=serpent,mode=ncfb,key=86 ba 60 e7 62 c0 af de 6c 55 0e cb 68 f1 4b 77 68 fb d2 77 1e 09 d1 ad,iv=2f 21 4b 2c 8c cd b4 51 87 71 81 f1 de c4 95 24,pt=03 b1 35 46 14,ct=64 6a 86 f0 19
algo=serpent,mode=ncfb,key=86 ba 60 e7 62 c0 af de 6c 55 0e cb 68 f1 4b 77 68 fb d2 77 1e 09 d1 ad,iv=2f 21 4b 2c 8c cd b4 51 87 71 81 f1 de c4 95 24,pt=b2 9d cc 06 6d af 33 49 92 68 a1 dd e3 65 c0 6e,ct=d5 46 7f b0 60 fa 35 73 a9 bf 4e e9 b4 39 20 15
algo=serpent,mode=ncfb,key=9f a4 c9 da 38 52 77 8a d6 f0 2a b1 20 fe 45 35 01 4b cf c3 c4 3e 26 50 01 4a ea 38 7e 52 cc a3,iv=94 c8 e5 44 5e eb fe 5d 1d 04 da 53 42 78 78 37,pt=65 52 6b 51 4b,ct=5e 80 ff 17 e4
algo=serpent,mode=ncfb,key=9f a4 c9 da 38 52 77 8a d6 f0 2a b1 20 fe 45 35 01 4b cf c3 c4 3e 26 50 01 4a ea 38 7e 52 cc a3,iv=94 c8 e5 44 5e eb fe 5d 1d 04 da 53 42 78 78 37,pt=b6 e1 62 86 5d 11 ac 26 fd ea 2e 33 84 0f 58 7e,ct=8d 33 f6 c0 f2 8f f5 e0 9e af b6 e7 07 59 25 1c
algo=serpent,mode=nofb,key=bf aa da b3 86 7e 67 58 db 14 ce e5 ab 5b a9 d8,iv=e5 d2 0f 48 c6 29 11 24 52 df aa f2 1f 68 83 96,pt=6a cd 73 0b db,ct=74 f2 e9 50 f0
algo=serpent,mode=nofb,key=bf aa da b3 86 7e 67 58 db 14 ce e5 ab 5b a9 d8,iv=e5 d2 0f 48 c6 29 11 24 52 df aa f2 1f 68 83 96,pt=1c 2c a1 5c 51 50 bc fb ab 46 e0 40 54 1a 55 ee,ct=02 13 3b 07 7a 64 90 58 4a c1 6c ab e5 5b 22 17
algo=serpent,mode=nofb,key=98 f4 f2 dc dc 1f 61 ce fd 86 a8 21 17 e3 1a f7 46 4b dc b7 1f 25 82 20,iv=3c 09 3f d3 8a 96 b2 6b 78 cc c5 6d 3a 42 f0 db,pt=36 e6 56 4d c1,ct=c3 42 2b 08 88
algo=serpent,mode=nofb,key=98 f4 f2 dc dc 1f 61 ce fd 86 a8 21 17 e3 1a f7 46 4b dc b7 1f 25 82 20,iv=3c 09 3f d3 8a 96 b2 6b 78 cc c5 6d 3a 42 f0 db,pt=27 e6 7c b6 a1 70 02 7b f7 4e 08 bc 59 4e 9b 8c,ct=d2 42 01 f3 e8 23 e5 13 06 44 0b 1b 83 4a d9 2a
algo=serpent,mode=nofb,key=c3 02 67 1c 76 ef 31 14 a1 0b 52 00 e6 0d b7 55 6c de 7d 52 a3 b5 3b fb f9 51 59 a6 05 be b4 5f,iv=3b 33 ee 26 95 b3 d9 5b 2e cd c0 35 61 30 e5 77,pt=93 8f 80 01 d1,ct=e6 4c 06 a5 00
algo=serpent,mode=nofb,key=c3 02 67 1c 76 ef 31 14 a1 0b 52 00 e6 0d b7 55 6c de 7d 52 a3 b5 3b fb f9 51 59 a6 05 be b4 5f,iv=3b 33 ee 26 95 b3 d9 5b 2e cd c0 35 61 30 e5 77,pt=eb 1c 01 db 5a 6f b6 52 b6 f5 33 e5 d4 b6 c9 4b,ct=9e df 87 7f 8b 41 c5 2d 43 1d 69 58 54 82 3c 97
algo=serpent,mode=ofb,key=f5 3c ce be 00 8f c5 37 c9 0b 42 bb 25 24 ec cf,iv=4b ac 19 ee d9 27 5d c9 b8 66 7b 39 73 ce 9f c5,pt=5a f3 65 ed bf,ct=3f 7c 6c 8f 5b
algo=serpent,mode=ofb,key=f5 3c ce be 00 8f c5 37 c9 0b 42 bb 25 24 ec cf,iv=4b ac 19 ee d9 27 5d c9 b8 66 7b 39 73 ce 9f c5,pt=65 18 9c 40 24 ac 4e 4e fd 90 8d c3 15 0e e8 d6,ct=00 97 95 22 c0 fa d3 55 52 f8 5c ff 36 f8 a9 3e
algo=serpent,mode=ofb,key=f9 b7 43 c6 11 48 3a 8d c6 9a 27 3b 8a a3 e7 5c 18 2c f4 92 aa 80 21 e6,iv=2c 31 0d dc 33 24 d7 55 ec 72 9d 50 c4 72 d2 a3,pt=c2 9a 49 11 97,ct=0f d2 c7 91 a3
algo=serpent,mode=ofb,key=f9 b7 43 c6 11 48 3a 8d c6 9a 27 3b 8a a3 e7 5c 18 2c f4 92 aa 80 21 e6,iv=2c 31 0d dc 33 24 d7 55 ec 72 9d 50 c4 72 d2 a3,pt=5a a1 ee b7 f2 9b 98 74 5b 12 fd 0c 2b 42 37 71,ct=97 e9 60 37 c6 d3 5a 96 1c f4 30 03 c8 f4 c6 10
algo=serpent,mode=ofb,key=fc bc ba cc 41 bb 6a 2a 15 e2 d2 07 19 d2 b6 69 5b f4 20 23 6e 24 c4 29 3c ba b3 b0 9e 88 3a 5d,iv=b4 4b 9b 43 40 35 c1 bc cf a6 8d 6a 78 34 1b af,pt=90 29 aa b2 04,ct=45 4d 7d 6f 00
algo=serpent,mode=ofb,key=fc bc ba cc 41 bb 6a 2a 15 e2 d2 07 19 d2 b6 69 5b f4 20 23 6e 24 c4 29 3c ba b3 b0 9e 88 3a 5d,iv=b4 4b 9b 43 40 35 c1 bc cf a6 8d 6a 78 34 1b af,pt=a0 f1 de 1f a4 66 80 fd 2f 62 7c 9e 58 89 32 d8,ct=75 95 09 c2 a0 4c b3 bd 8f 4c 7c 92 ae 51 18 17
algo=xtea,mode=cbc,key=3e d6 2c 5b de e6 45 67 e7 cc 9d 08 65 0d 6c 92,iv=50 af 59 27 82 b8 85 ef,pt=4e e7 a7 4c 04 93 e9 47,ct=46 68 d7 8e 67 a0 bb 65
algo=xtea,mode=cfb,key=eb 44 ec a3 f3 17 6c 86 ee 57 c1 54 98 64 d3 01,iv=e8 f4 16 c5 de 29 c1 0f,pt=20 a3 db f2 bf,ct=d5 a6 81 cb b0
algo=xtea,mode=cfb,key=eb 44 ec a3 f3 17 6c 86 ee 57 c1 54 98 64 d3 01,iv=e8 f4 16 c5 de 29 c1 0f,pt=1c cc ca 9e ba 84 cc 2f,ct=e9 f6 25 5e 9c 87 62 80
algo=xtea,mode=ctr,key=58 62 e2 c2 4c 13 d2 2a d2 bf 90 01 5b 2d 98 65,iv=ca 12 10 46 e5 90 75 ab,pt=79 f4 14 f8 db,ct=12 5e 63 fe de
algo=xtea,mode=ctr,key=58 62 e2 c2 4c 13 d2 2a d2 bf 90 01 5b 2d 98 65,iv=ca 12 10 46 e5 90 75 ab,pt=e1 d7 d2 a4 5d 78 15 e9,ct=8a 7d a5 a2 58 a7 06 31
algo=xtea,mode=ecb,key=2a 22 a0 9d 76 c0 5a 0a 0f 61 96 3c 01 b5 bb 17,iv=a8 9b de c9 b3 d0 8f 65,pt=fc 17 0f d3 57 5d a7 cc,ct=8b fb a8 fa c6 21 42 ea
algo=xtea,mode=ncfb,key=a4 f7 22 06 1c 8c 6f 13 e7 3b fd a3 30 04 57 50,iv=51 42 40 9e 90 73 88 15,pt=60 d7 6a 4d e3,ct=e9 c4 99 11 e2
algo=xtea,mode=ncfb,key=a4 f7 22 06 1c 8c 6f 13 e7 3b fd a3 30 04 57 50,iv=51 42 40 9e 90 73 88 15,pt=4e 9a 4a be 30 e6 0e 29,ct=c7 89 b9 e2 31 a3 df 4f
algo=xtea,mode=nofb,key=d9 ae c7 14 4a 85 f3 c9 ad bb e8 e4 86 90 cb 4d,iv=71 cf 06 2e b5 96 45 9c,pt=d8 6a 23 f3 31,ct=99 45 f0 1d 69
algo=xtea,mode=nofb,key=d9 ae c7 14 4a 85 f3 c9 ad bb e8 e4 86 90 cb 4d,iv=71 cf 06 2e b5 96 45 9c,pt=aa 62 8d 5e 45 18 37 b2,ct=eb 4d 5e b0 1d c3 4e 6a
algo=xtea,mode=ofb,key=54 49 3d 75 dd 1c 82 c0 b2 29 a8 1d de 00 60 86,iv=4e 1b c3 cb fb 36 08 d8,pt=fd f3 46 bb 57,ct=01 7c b7 f7 a4
algo=xtea,mode=ofb,key=54 49 3d 75 dd 1c 82 c0 b2 29 a8 1d de 00 60 86,iv=4e 1b c3 cb fb 36 08 d8,pt=9e 95 f2 b7 66 53 65 5d,ct=62 1a 03 fb 95 aa 5b 2d
algo=tripledes,mode=cbc,key=07 3c 39 ae 30 18 f1 3a 95 18 f4 2d d9 80 d9 65 a4 29 64 87 39 3a f0 84,iv=f3 90 26 59 e4 32 1e cf,pt=f4 eb 85 fb bc 88 7e 72,ct=d9 6c c7 2c f8 04 c9 cc
algo=tripledes,mode=cfb,key=5e 13 58 67 fa 69 0d d4 46 a1 cc af 36 de 4e 7f 03 43 6e d5 08 3b 6a 1d,iv=c6 8f 32 d2 07 f6 a3 b0,pt=39 e5 21 81 b2,ct=97 7e 4d c6 0a
algo=tripledes,mode=cfb,key=5e 13 58 67 fa 69 0d d4 46 a1 cc af 36 de 4e 7f 03 43 6e d5 08 3b 6a 1d,iv=c6 8f 32 d2 07 f6 a3 b0,pt=b7 32 a6 df 74 31 9c e8,ct=19 5d 7b 3e 72 ac 46 d4
algo=tripledes,mode=ctr,key=75 f1 55 4e b3 95 61 c7 6e b7 af 5e 52 35 5a 78 12 8a 6e 2a 23 d4 32 b6,iv=7a 62 aa cf 23 93 96 b9,pt=4c 10 ab 90 fe,ct=3f fc ff 13 4e
algo=tripledes,mode=ctr,key=75 f1 55 4e b3 95 61 c7 6e b7 af 5e 52 35 5a 78 12 8a 6e 2a 23 d4 32 b6,iv=7a 62 aa cf 23 93 96 b9,pt=b2 01 67 2d f4 ad 4d e3,ct=c1 ed 33 ae 44 51 d9 cf
algo=tripledes,mode=ecb,key=3a a1 b0 02 ac 81 e4 8d 18 bb 49 3f 6d 40 85 a9 63 94 e9 8a e5 ae 8c a4,iv=08 6d ad bf 93 8f 3c e6,pt=ed 1a 67 07 34 be 4a 5a,ct=1e 39 06 f0 5c e4 9f 4a
algo=tripledes,mode=ncfb,key=4b 89 1b 7b 64 14 ce 6f a7 d2 92 da 08 a7 36 9c b6 91 84 46 e6 33 1e 72,iv=ca 46 85 bf e3 b7 c0 e2,pt=ab 7f 9b ce 8f,ct=f9 81 1f e6 0c
algo=tripledes,mode=ncfb,key=4b 89 1b 7b 64 14 ce 6f a7 d2 92 da 08 a7 36 9c b6 91 84 46 e6 33 1e 72,iv=ca 46 85 bf e3 b7 c0 e2,pt=7f 4b 86 3a fd 73 7e f0,ct=2d b5 02 12 7e f7 cb aa
algo=tripledes,mode=nofb,key=98 6f 35 92 f5 69 18 31 69 bd f5 6a 82 6e 10 b3 e5 27 27 9e 49 01 4b eb,iv=1d e5 56 19 34 34 ba 6b,pt=b5 b2 9c cf 2f,ct=7c b5 95 5c 1c
algo=tripledes,mode=nofb,key=98 6f 35 92 f5 69 18 31 69 bd f5 6a 82 6e 10 b3 e5 27 27 9e 49 01 4b eb,iv=1d e5 56 19 34 34 ba 6b,pt=aa 72 98 57 eb 75 40 c9,ct=63 75 91 c4 d8 49 72 f7
algo=tripledes,mode=ofb,key=f1 bf 20 e0 b8 0b 71 bd 94 85 5f ab c0 9a b3 56 5a 1f 08 28 5d 12 35 d9,iv=08 43 ae 8f 6b 5a fd 3a,pt=d4 fd 43 75 0c,ct=e7 e0 d3 15 a8
algo=tripledes,mode=ofb,key=f1 bf 20 e0 b8 0b 71 bd 94 85 5f ab c0 9a b3 56 5a 1f 08 28 5d 12 35 d9,iv=08 43 ae 8f 6b 5a fd 3a,pt=cd 16 7d 7e a3 48 83 bf,ct=fe 0b ed 1e 07 13 8d 44
